// data.js - Base de données complète du programme L'Avenir en commun
// Version 1.0 - 50 mesures prioritaires

const mesures = [
  // === TRAVAIL & RETRAITE (10) ===
  {
    "id": 1,
    "titre": "Retraite à 60 ans",
    "categorie": "travail",
    "sous_categorie": "retraite",
    "public": ["seniors", "actifs"],
    "resume": "Retour à la retraite à 60 ans avec 40 annuités de cotisation.",
    "explication": "La réforme Macron qui repoussait l'âge à 64 ans est abrogée. On revient au système antérieur : départ possible à 60 ans pour une carrière complète de 40 ans. Les métiers pénibles conservent des départs anticipés.",
    "chiffre_cle": "83% des Français soutiennent une pension minimale au niveau du SMIC",
    "exemple_concret": "Mme Martin, aide-soignante, a commencé à 20 ans. Elle pourra partir à 60 ans avec 1450€ net (contre 64 ans et 980€ aujourd'hui).",
    "financement": "Augmentation de 0,25 point par an des cotisations vieillesse + soumission des dividendes à cotisation",
    "url": "/2100/mesures/retraite-60-ans.html",
    "motscles": ["retraite", "60 ans", "pension", "senior", "carrière longue", "départ anticipé"],
    "statut": "mesure_cle"
  },
  {
    "id": 2,
    "titre": "SMIC à 1600€ net",
    "categorie": "travail",
    "sous_categorie": "salaire",
    "public": ["actifs", "jeunes"],
    "resume": "Augmentation immédiate du SMIC à 1600 euros net par mois.",
    "explication": "Le SMIC est porté à 1600€ net dès l'arrivée au pouvoir. Cette augmentation bénéficie directement à 2,3 millions de salariés et tire tous les salaires inférieurs à 2000€ vers le haut (effet d'entraînement).",
    "chiffre_cle": "56% des salariés français gagnent moins de 2000€ net par mois",
    "exemple_concret": "Un caissier au SMIC passe de 1210€ à 1600€ net par mois, soit +390€.",
    "financement": "Hausse du SMIC = 1,8Md€ par an pour l'État (compensé par les recettes fiscales supplémentaires et la croissance)",
    "url": "/2100/mesures/smic-1600.html",
    "motscles": ["SMIC", "salaire", "pouvoir d'achat", "1600 euros", "bas salaires"],
    "statut": "mesure_cle"
  },
  {
    "id": 3,
    "titre": "Semaine de 4 jours (32 heures)",
    "categorie": "travail",
    "sous_categorie": "temps_de_travail",
    "public": ["actifs"],
    "resume": "Passage aux 32 heures pour les métiers pénibles, généralisation négociée.",
    "explication": "Les 32 heures deviennent la norme pour les métiers pénibles et le travail de nuit. Une conférence nationale sur le partage du temps de travail décidera des modalités et du calendrier de la transition vers les 32 heures pour tous.",
    "chiffre_cle": "70% des Français sont favorables à la semaine de 4 jours (Ifop, 2024)",
    "exemple_concret": "Un ouvrier du bâtiment travaillant de nuit passe de 35h à 32h sans perte de salaire.",
    "financement": "Financement par les gains de productivité et la réduction du chômage",
    "url": "/2100/mesures/semaine-4-jours.html",
    "motscles": ["32 heures", "semaine de 4 jours", "temps de travail", "pénibilité", "travail de nuit"],
    "statut": "mesure_cle"
  },
  {
    "id": 4,
    "titre": "Fin des CDD précaires",
    "categorie": "travail",
    "sous_categorie": "emploi",
    "public": ["actifs", "jeunes"],
    "resume": "Quota maximal de contrats précaires : 10% dans les PME, 5% dans les grandes entreprises.",
    "explication": "Pour lutter contre la précarisation massive, un quota limite le recours aux CDD, intérim et contrats courts. Les entreprises doivent embaucher en CDI pour leurs missions pérennes.",
    "chiffre_cle": "87% des embauches se font en contrats courts",
    "exemple_concret": "Une grande surface qui emploie 200 personnes ne pourra avoir que 10 CDD (5%) au lieu de 80 aujourd'hui.",
    "financement": "Sans coût pour l'État - simple réallocation des contrats",
    "url": "/2100/mesures/fin-cdd-precaires.html",
    "motscles": ["CDD", "précarité", "intérim", "CDI", "contrat court"],
    "statut": "mesure_cle"
  },
  {
    "id": 5,
    "titre": "Garantie d'emploi pour les chômeurs de longue durée",
    "categorie": "travail",
    "sous_categorie": "emploi",
    "public": ["chomeurs"],
    "resume": "Tout chômeur de longue durée peut se voir proposer un emploi utile, payé au SMIC.",
    "explication": "L'État garantit un emploi dans un secteur utile (écologie, social, services publics) à tout chômeur volontaire après 12 mois d'inscription. Emploi à temps choisi (20-35h/semaine).",
    "chiffre_cle": "87% des Français soutiennent cette mesure",
    "exemple_concret": "Un informaticien au chômage depuis 14 mois peut être embauché pour former des seniors au numérique dans une association.",
    "financement": "18 milliards d'euros par an pour 1,8 million d'emplois",
    "url": "/2100/mesures/garantie-emploi.html",
    "motscles": ["chômage", "chômeur", "garantie d'emploi", "insertion", "longue durée"],
    "statut": "mesure_cle"
  },
  {
    "id": 6,
    "titre": "Rétablissement d'une assurance chômage protectrice",
    "categorie": "travail",
    "sous_categorie": "chomage",
    "public": ["chomeurs", "actifs"],
    "resume": "Indemnisation dès le premier jour, calculée sur les derniers salaires, fin des radiations abusives.",
    "explication": "Abrogation des réformes Macron de l'assurance chômage. Retour à une indemnisation protectrice : pas de délai de carence, calcul sur les 12 derniers mois travaillés, fin de la dégressibilité pour les cadres.",
    "chiffre_cle": "14 000 personnes meurent chaque année des conséquences du chômage",
    "exemple_concret": "Un cadre perd son emploi : son allocation ne diminue plus après 6 mois.",
    "financement": "Redistribution des 6 milliards d'euros prélevés sur l'Unédic par l'État",
    "url": "/2100/mesures/assurance-chomage-protectrice.html",
    "motscles": ["chômage", "assurance chômage", "indemnisation", "Pôle emploi", "radiation"],
    "statut": "mesure_cle"
  },
  {
    "id": 7,
    "titre": "Sécurité sociale professionnelle",
    "categorie": "travail",
    "sous_categorie": "formation",
    "public": ["actifs", "chomeurs"],
    "resume": "Les droits sociaux (formation, congés, ancienneté) sont attachés à la personne, pas au contrat.",
    "explication": "Comme la carte Vitale garantit la continuité des droits santé, la sécurité sociale professionnelle garantit les droits à la formation, aux congés et à l'ancienneté tout au long de la vie, y compris entre deux contrats.",
    "chiffre_cle": "Droit à 36 heures de formation par an par salarié",
    "exemple_concret": "Un intérimaire cumule ses droits à formation même entre deux missions.",
    "financement": "Financement par les cotisations sociales des entreprises",
    "url": "/2100/mesures/securite-sociale-professionnelle.html",
    "motscles": ["formation", "droits sociaux", "carrière", "intérim", "précarité"],
    "statut": "mesure"
  },
  {
    "id": 8,
    "titre": "Fin du travail détaché",
    "categorie": "travail",
    "sous_categorie": "emploi",
    "public": ["actifs"],
    "resume": "Un travailleur sur le sol français paie les cotisations françaises et a les mêmes droits.",
    "explication": "Le système du travail détaché, qui permet à des entreprises de faire travailler des étrangers avec les cotisations du pays d'origine, est aboli. Tous les travailleurs sur le territoire français bénéficient des mêmes droits et cotisations.",
    "chiffre_cle": "68% des Français sont favorables à l'interdiction du travail détaché",
    "exemple_concret": "Un ouvrier polonais sur un chantier en France cotise à la Sécu française et touche les mêmes indemnités qu'un ouvrier français.",
    "financement": "Sans coût - rééquilibrage des cotisations",
    "url": "/2100/mesures/fin-travail-detache.html",
    "motscles": ["travail détaché", "dumping social", "cotisations", "travailleurs étrangers"],
    "statut": "mesure"
  },
  {
    "id": 9,
    "titre": "Reconnaissance du burn-out en maladie professionnelle",
    "categorie": "travail",
    "sous_categorie": "sante_travail",
    "public": ["actifs"],
    "resume": "Le burn-out est reconnu comme maladie professionnelle, avec prise en charge et indemnisation.",
    "explication": "L'épuisement professionnel (burn-out) entre dans le tableau des maladies professionnelles. Les victimes bénéficient d'une prise en charge par la Sécu, d'une indemnisation et d'un parcours de soins adapté.",
    "chiffre_cle": "81% des Français soutiennent cette mesure",
    "exemple_concret": "Un salarié en burn-out est reconnu en arrêt maladie professionnelle avec indemnisation à 100% du salaire.",
    "financement": "Prise en charge par la branche AT/MP de la Sécu",
    "url": "/2100/mesures/burnout-maladie-professionnelle.html",
    "motscles": ["burn-out", "épuisement", "santé mentale", "maladie professionnelle", "stress"],
    "statut": "mesure"
  },
  {
    "id": 10,
    "titre": "35 heures effectives",
    "categorie": "travail",
    "sous_categorie": "temps_de_travail",
    "public": ["actifs"],
    "resume": "Rétablissement des 35 heures comme norme, fin des heures supplémentaires défiscalisées.",
    "explication": "Les heures supplémentaires sont majorées à 25% pour les 4 premières et 50% au-delà. Fin du contournement des 35 heures par l'annualisation et les forfaits-jours abusifs.",
    "chiffre_cle": "Les Français travaillent en moyenne 37h par semaine",
    "exemple_concret": "Un employé en forfait-jours abusif retrouve un décompte horaire et des majorations pour heures sup.",
    "financement": "Sans coût - création d'emplois par partage du travail",
    "url": "/2100/mesures/35-heures-effectives.html",
    "motscles": ["35 heures", "heures supplémentaires", "forfait jours", "annualisation"],
    "statut": "mesure"
  },

  // === ÉCOLOGIE & CLIMAT (12) ===
  {
    "id": 11,
    "titre": "100% énergies renouvelables en 2050",
    "categorie": "ecologie",
    "sous_categorie": "energie",
    "public": ["tous"],
    "resume": "Objectif 100% d'énergies renouvelables en 2050, sortie du nucléaire et des énergies fossiles.",
    "explication": "La France s'engage à atteindre 100% d'énergies renouvelables (solaire, éolien, hydrolien, géothermie) d'ici 2050. Sortie progressive du nucléaire et arrêt des subventions aux énergies fossiles.",
    "chiffre_cle": "74% des Français sont favorables à un objectif 100% renouvelable",
    "exemple_concret": "La Réunion, territoire pilote, atteint 100% d'énergies renouvelables grâce au solaire, l'hydrolien et la géothermie.",
    "financement": "93 milliards d'euros d'investissement sur le quinquennat",
    "url": "/2100/mesures/100-renouvelables.html",
    "motscles": ["énergies renouvelables", "solaire", "éolien", "sortie nucléaire", "transition énergétique"],
    "statut": "mesure_cle"
  },
  {
    "id": 12,
    "titre": "Rénovation thermique des logements",
    "categorie": "ecologie",
    "sous_categorie": "logement",
    "public": ["tous", "seniors", "precaires"],
    "resume": "700 000 logements rénovés par an, interdiction de location des passoires thermiques.",
    "explication": "Plan massif de rénovation énergétique : 700 000 logements par an sont isolés thermiquement. Les passoires thermiques (classes F et G) ne pourront plus être louées à partir de 2025. Aides à 100% pour les ménages modestes.",
    "chiffre_cle": "4,8 millions de passoires thermiques en France",
    "exemple_concret": "Un propriétaire d'un appartement classé G reçoit des aides pour l'isolation avant de pouvoir le relouer.",
    "financement": "Inclus dans le plan d'investissement écologique",
    "url": "/2100/mesures/renovation-thermique.html",
    "motscles": ["rénovation", "isolation", "passoire thermique", "énergie", "logement", "DPE"],
    "statut": "mesure_cle"
  },
  {
    "id": 13,
    "titre": "Interdiction du glyphosate",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Interdiction immédiate du glyphosate et des néonicotinoïdes, y compris dans les produits importés.",
    "explication": "Le glyphosate et les néonicotinoïdes sont interdits en France dès l'arrivée au pouvoir. L'interdiction s'applique aussi aux produits importés pour éviter le dumping. Un plan d'accompagnement aide les agriculteurs à se convertir.",
    "chiffre_cle": "89% des Français sont favorables à l'interdiction du glyphosate",
    "exemple_concret": "Un agriculteur utilisant du glyphosate reçoit une aide pour passer au désherbage mécanique.",
    "financement": "Caisse de défaisance pour les agriculteurs convertis au bio",
    "url": "/2100/mesures/interdiction-glyphosate.html",
    "motscles": ["glyphosate", "pesticides", "néonicotinoïdes", "agriculture", "bio"],
    "statut": "mesure_cle"
  },
  {
    "id": 14,
    "titre": "Sortie des fermes-usines",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Interdiction des élevages intensifs et sortie progressive des fermes-usines d'ici 2027.",
    "explication": "Les fermes-usines (élevages de plus de 150 truies ou vaches laitières, élevages en cage, etc.) sont interdites. Un accompagnement financier aide les éleveurs à se reconvertir vers des élevages extensifs ou des cultures végétales.",
    "chiffre_cle": "80% des animaux d'élevage sont en élevage intensif",
    "exemple_concret": "Un éleveur de porcs en batterie reçoit une aide pour passer à un élevage plein air.",
    "financement": "Aide à la transition budgétée dans le plan agricole",
    "url": "/2100/mesures/sortie-fermes-usines.html",
    "motscles": ["ferme-usine", "élevage intensif", "bien-être animal", "agro-industrie"],
    "statut": "mesure_cle"
  },
  {
    "id": 15,
    "titre": "Règle verte dans la Constitution",
    "categorie": "ecologie",
    "sous_categorie": "institutions",
    "public": ["tous"],
    "resume": "Inscription dans la Constitution du principe : ne pas prendre à la nature plus qu'elle ne peut reconstituer.",
    "explication": "La 'règle verte' devient un principe constitutionnel. Toute loi, tout projet d'infrastructure doit respecter cette limite. Le droit de propriété ne peut prévaloir sur la protection de l'eau, l'air, la biodiversité.",
    "chiffre_cle": "83% des Français soutiennent ce principe",
    "exemple_concret": "Un projet d'autoroute pourrait être annulé s'il détruit une zone humide indispensable au cycle de l'eau.",
    "financement": "Sans coût direct - changement de paradigme juridique",
    "url": "/2100/mesures/regle-verte-constitution.html",
    "motscles": ["règle verte", "Constitution", "limites planétaires", "biodiversité", "écologie"],
    "statut": "mesure_cle"
  },
  {
    "id": 16,
    "titre": "Zéro artificialisation nette des sols",
    "categorie": "ecologie",
    "sous_categorie": "amenagement",
    "public": ["tous"],
    "resume": "Interdiction du bétonnage des terres agricoles et naturelles dès 2025.",
    "explication": "Plus aucune construction ne peut artificialiser des terres agricoles ou naturelles. Les constructions nouvelles doivent se faire sur des friches ou des terrains déjà artificialisés.",
    "chiffre_cle": "20 000 à 30 000 hectares artificialisés chaque année en France",
    "exemple_concret": "Un entrepôt Amazon ne peut plus s'installer sur une terre agricole. Il doit reconvertir une friche industrielle.",
    "financement": "Sans coût - réorientation de l'aménagement",
    "url": "/2100/mesures/zero-artificialisation.html",
    "motscles": ["artificialisation", "bétonnage", "sols", "agriculture", "urbanisme"],
    "statut": "mesure"
  },
  {
    "id": 17,
    "titre": "Fin des vols intérieurs",
    "categorie": "ecologie",
    "sous_categorie": "transports",
    "public": ["tous"],
    "resume": "Suppression des lignes aériennes intérieures quand une alternative en train existe en moins de 4h.",
    "explication": "Les vols intérieurs sont supprimés lorsqu'un trajet en train de moins de 4 heures est possible. Cette mesure, demandée par la Convention citoyenne pour le climat, réduit massivement les émissions du transport aérien.",
    "chiffre_cle": "Le secteur des transports pèse 31% des émissions de gaz à effet de serre",
    "exemple_concret": "Paris-Lyon en avion est supprimé : les voyageurs prennent le TGV (2h).",
    "financement": "Sans coût - report modal vers le train",
    "url": "/2100/mesures/fin-vols-interieurs.html",
    "motscles": ["vol intérieur", "avion", "train", "TGV", "Convention citoyenne pour le climat"],
    "statut": "mesure"
  },
  {
    "id": 18,
    "titre": "Développement du fret ferroviaire",
    "categorie": "ecologie",
    "sous_categorie": "transports",
    "public": ["tous"],
    "resume": "Plan massif pour passer de 9% à 18% de fret ferroviaire, réouverture des gares de triage.",
    "explication": "Investissement massif dans le fret ferroviaire pour sortir des camions. Réouverture des gares de triage, retour du wagon isolé, développement du ferroutage.",
    "chiffre_cle": "9% du fret est ferroviaire en France contre 18% en moyenne européenne",
    "exemple_concret": "Les camions traversant la France entre l'Espagne et le Nord sont reportés sur le train.",
    "financement": "44 milliards d'euros sur le quinquennat",
    "url": "/2100/mesures/fret-ferroviaire.html",
    "motscles": ["fret", "train", "camion", "logistique", "ferroutage"],
    "statut": "mesure"
  },
  {
    "id": 19,
    "titre": "Plan eau : gratuité des premiers m³",
    "categorie": "ecologie",
    "sous_categorie": "eau",
    "public": ["tous", "precaires"],
    "resume": "Gratuité des premiers mètres cubes d'eau indispensables à la vie, tarification progressive.",
    "explication": "L'eau est un bien commun : les premiers m³ nécessaires à une vie digne (boisson, hygiène, cuisine) sont gratuits. Au-delà, une tarification progressive pénalise les usages abusifs (piscines, arrosage intensif).",
    "chiffre_cle": "80% des Français soutiennent la gratuité des premiers m³",
    "exemple_concret": "Une famille de 4 personnes ne paie plus pour ses 120 premiers m³ par an (usage domestique normal).",
    "financement": "Financé par la tarification progressive et le retour en régie publique",
    "url": "/2100/mesures/plan-eau.html",
    "motscles": ["eau", "gratuité", "tarification progressive", "bien commun", "régie publique"],
    "statut": "mesure"
  },
  {
    "id": 20,
    "titre": "Interdiction des plastiques à usage unique",
    "categorie": "ecologie",
    "sous_categorie": "dechets",
    "public": ["tous"],
    "resume": "Interdiction immédiate de tous les plastiques à usage unique, généralisation de la consigne.",
    "explication": "Les plastiques à usage unique (gobelets, couverts, pailles, emballages jetables) sont interdits. La consigne pour les bouteilles et bocaux en verre est généralisée.",
    "chiffre_cle": "360 millions de tonnes de plastique produites chaque année dans le monde",
    "exemple_concret": "Au supermarché, plus de suremballage : les légumes sont en vrac, les bouteilles sont consignées.",
    "financement": "Soutien aux filières de réemploi",
    "url": "/2100/mesures/fin-plastiques-usage-unique.html",
    "motscles": ["plastique", "usage unique", "consigne", "déchets", "suremballage"],
    "statut": "mesure"
  },
  {
    "id": 21,
    "titre": "Moratoire sur les OGM",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Moratoire sur tous les OGM, y compris les 'OGM cachés' issus des nouvelles techniques génomiques.",
    "explication": "Tous les OGM sont interdits, y compris ceux issus des nouvelles techniques génomiques (NBT). La recherche publique sur les alternatives est renforcée.",
    "chiffre_cle": "La France est le premier consommateur européen de produits sans OGM",
    "exemple_concret": "Un agriculteur ne peut plus planter de maïs OGM, même les variétés issues de mutagénèse.",
    "financement": "Sans coût - réorientation de la recherche",
    "url": "/2100/mesures/moratoire-ogm.html",
    "motscles": ["OGM", "NBT", "mutagénèse", "semences", "agriculture"],
    "statut": "mesure"
  },
  {
    "id": 22,
    "titre": "ISF climatique",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["riches"],
    "resume": "Rétablissement de l'ISF avec un volet climatique taxant les actifs polluants.",
    "explication": "L'ISF supprimé par Macron est rétabli. Un volet climatique ajoute une taxation sur les actifs liés aux énergies fossiles, aux mines, à la déforestation.",
    "chiffre_cle": "Les 10% les plus riches polluent 5 fois plus que la moitié la plus pauvre",
    "exemple_concret": "Un portefeuille d'actions contenant du pétrole est plus taxé qu'un portefeuille vert.",
    "financement": "10 milliards d'euros par an",
    "url": "/2100/mesures/isf-climatique.html",
    "motscles": ["ISF", "impôt", "riches", "climat", "actifs polluants"],
    "statut": "mesure_cle"
  },

  // === SANTÉ (6) ===
  {
    "id": 23,
    "titre": "100% Sécu",
    "categorie": "sante",
    "sous_categorie": "remboursement",
    "public": ["tous", "precaires", "seniors"],
    "resume": "Remboursement intégral de tous les soins prescrits par la Sécurité sociale.",
    "explication": "Fin des tickets modérateurs et des restes à charge. Tous les soins prescrits (médecine, dentaire, optique, audioprothèse) sont remboursés à 100% par la Sécu. Les mutuelles sont intégrées au système public.",
    "chiffre_cle": "59% des Français ont renoncé à des soins pour raisons financières",
    "exemple_concret": "Une paire de lunettes à 300€ : fin du reste à charge de 150€, tout est remboursé.",
    "financement": "14,35 milliards d'euros par an, financé par la fin des frais de gestion des mutuelles et la régulation des prix",
    "url": "/2100/mesures/100-secu.html",
    "motscles": ["Sécu", "remboursement", "mutuelle", "soins", "déserts médicaux"],
    "statut": "mesure_cle"
  },
  {
    "id": 24,
    "titre": "Fin des déserts médicaux",
    "categorie": "sante",
    "sous_categorie": "acces_soins",
    "public": ["tous", "ruraux", "precaires"],
    "resume": "Maillage du territoire en centres de santé publics, fin des déserts médicaux en 5 ans.",
    "explication": "Création de centres de santé pluridisciplinaires publics partout en France. Recrutement de médecins publics. Augmentation du numerus clausus. Obligation de permanence des soins.",
    "chiffre_cle": "1 Français sur 5 vit dans un désert médical",
    "exemple_concret": "Dans un village sans médecin, un centre de santé public ouvre avec 3 généralistes et 2 infirmiers.",
    "financement": "Inclus dans le plan de recrutement des soignants (100 000 postes)",
    "url": "/2100/mesures/fin-deserts-medicaux.html",
    "motscles": ["désert médical", "médecin", "centre de santé", "accès aux soins", "numerus clausus"],
    "statut": "mesure_cle"
  },
  {
    "id": 25,
    "titre": "Légalisation du cannabis",
    "categorie": "sante",
    "sous_categorie": "addictions",
    "public": ["tous"],
    "resume": "Légalisation encadrée du cannabis (production, vente, consommation) sous monopole d'État.",
    "explication": "Le cannabis est légalisé sous contrôle de l'État. La production, la vente et la consommation sont régulées. Les recettes fiscales financent la prévention et la lutte contre les addictions.",
    "chiffre_cle": "57% des Français soutiennent la légalisation",
    "exemple_concret": "Un consommateur peut acheter du cannabis dans un bureau de tabac agréé, avec un prix fixé par l'État.",
    "financement": "Les taxes rapportent 5 milliards d'euros par an",
    "url": "/2100/mesures/legalisation-cannabis.html",
    "motscles": ["cannabis", "légalisation", "drogue", "prévention", "addiction"],
    "statut": "mesure"
  },
  {
    "id": 26,
    "titre": "Pôle public du médicament",
    "categorie": "sante",
    "sous_categorie": "medicaments",
    "public": ["tous"],
    "resume": "Création d'un pôle public pour produire les médicaments essentiels en France.",
    "explication": "Un pôle public du médicament est créé pour relocaliser la production des médicaments essentiels (antibiotiques, vaccins, paracétamol). Fin des pénuries et des prix abusifs.",
    "chiffre_cle": "80% des médicaments remboursés sont importés",
    "exemple_concret": "Lors d'une pénurie de doliprane, le pôle public relance la production en France.",
    "financement": "Nationalisation des filiales critiques, financement public",
    "url": "/2100/mesures/pole-public-medicament.html",
    "motscles": ["médicament", "pénurie", "relocalisation", "doliprane", "vaccin"],
    "statut": "mesure"
  },
  {
    "id": 27,
    "titre": "Droit de mourir dans la dignité",
    "categorie": "sante",
    "sous_categorie": "fin_de_vie",
    "public": ["seniors", "tous"],
    "resume": "Constitutionnalisation du droit de mourir dans la dignité et aide à mourir légalisée.",
    "explication": "Le droit à mourir dans la dignité est inscrit dans la Constitution. L'aide médicale à mourir (euthanasie et suicide assisté) est légalisée, encadrée et accessible.",
    "chiffre_cle": "89% des Français soutiennent l'euthanasie, 92% le suicide assisté",
    "exemple_concret": "Un patient en phase terminale peut demander une aide médicale à mourir, après avis collégial.",
    "financement": "Sans coût supplémentaire",
    "url": "/2100/mesures/droit-mourir-dignite.html",
    "motscles": ["fin de vie", "euthanasie", "suicide assisté", "dignité", "soins palliatifs"],
    "statut": "mesure"
  },
  {
    "id": 28,
    "titre": "Plan santé mentale",
    "categorie": "sante",
    "sous_categorie": "sante_mentale",
    "public": ["tous", "jeunes"],
    "resume": "Réouverture des lits de psychiatrie, recrutement de psychologues, renforcement des CMP.",
    "explication": "Plan d'urgence pour la santé mentale : réouverture des lits fermés, recrutement massif de psychologues et de psychiatres, renforcement des centres médico-psychologiques (CMP) partout sur le territoire.",
    "chiffre_cle": "20% de la population souffre de troubles psychiques dans sa vie",
    "exemple_concret": "Un adolescent en dépression peut consulter un psychologue gratuitement dans son CMP de secteur.",
    "financement": "Inclus dans le plan de recrutement des soignants",
    "url": "/2100/mesures/plan-sante-mentale.html",
    "motscles": ["santé mentale", "psychiatrie", "psychologue", "CMP", "dépression"],
    "statut": "mesure"
  },

  // === ÉDUCATION (5) ===
  {
    "id": 29,
    "titre": "Fin de Parcoursup",
    "categorie": "education",
    "sous_categorie": "enseignement_superieur",
    "public": ["jeunes"],
    "resume": "Suppression de Parcoursup, accès sans sélection à l'université pour tous les bacheliers.",
    "explication": "Parcoursup est supprimé. Tout bachelier peut s'inscrire dans la formation de son choix. Les capacités d'accueil des universités sont augmentées pour répondre aux besoins.",
    "chiffre_cle": "76% des Français soutiennent la suppression de Parcoursup",
    "exemple_concret": "Un bachelier peut s'inscrire directement en licence de psychologie, sans passer par un algorithme de sélection.",
    "financement": "Augmentation des moyens des universités (30 000 recrutements)",
    "url": "/2100/mesures/fin-parcoursup.html",
    "motscles": ["Parcoursup", "université", "sélection", "bachelier", "études supérieures"],
    "statut": "mesure_cle"
  },
  {
    "id": 30,
    "titre": "Recrutement de 160 000 enseignants",
    "categorie": "education",
    "sous_categorie": "personnels",
    "public": ["jeunes", "parents"],
    "resume": "Recrutement massif d'enseignants pour réduire les effectifs par classe.",
    "explication": "160 000 enseignants sont recrutés sur le quinquennat pour atteindre une moyenne de 19 élèves par classe (contre 24 aujourd'hui dans certains établissements). Priorité aux maternelles et aux REP.",
    "chiffre_cle": "60 000 recrutements immédiats dès la première année",
    "exemple_concret": "Dans une école maternelle de REP, une classe de 30 élèves passe à 19 élèves avec deux enseignants.",
    "financement": "26,5 milliards d'euros par an",
    "url": "/2100/mesures/recrutement-enseignants.html",
    "motscles": ["enseignant", "recrutement", "effectifs", "classe", "REP"],
    "statut": "mesure_cle"
  },
  {
    "id": 31,
    "titre": "Gratuité des cantines et fournitures scolaires",
    "categorie": "education",
    "sous_categorie": "gratuite",
    "public": ["parents", "jeunes"],
    "resume": "Cantines scolaires gratuites, fournitures et manuels gratuits.",
    "explication": "L'école devient réellement gratuite : cantine, fournitures, manuels, transports scolaires, sorties. Fin des inégalités entre élèves.",
    "chiffre_cle": "67% des Français soutiennent la gratuité intégrale de l'école",
    "exemple_concret": "Une famille avec 3 enfants ne paie plus 600€ par an de cantine et 300€ de fournitures.",
    "financement": "5,2 milliards d'euros par an",
    "url": "/2100/mesures/gratuite-ecole.html",
    "motscles": ["cantine", "fournitures", "gratuité", "école", "manuels"],
    "statut": "mesure"
  },
  {
    "id": 32,
    "titre": "Bac pro en 4 ans",
    "categorie": "education",
    "sous_categorie": "professionnel",
    "public": ["jeunes"],
    "resume": "Rétablissement du bac professionnel en 4 ans avec renforcement des enseignements généraux.",
    "explication": "Le bac pro repasse à 4 ans (contre 3 ans actuellement). Les enseignements généraux sont renforcés pour une meilleure qualification durable.",
    "chiffre_cle": "La moitié des lycéens sont en voie professionnelle",
    "exemple_concret": "Un élève de bac pro cuisine a 4 ans pour apprendre son métier et consolider son français, maths et histoire.",
    "financement": "5 milliards d'euros d'investissement dans les lycées professionnels",
    "url": "/2100/mesures/bac-pro-4-ans.html",
    "motscles": ["bac pro", "enseignement professionnel", "lycée pro", "CAP", "formation"],
    "statut": "mesure"
  },
  {
    "id": 33,
    "titre": "Garantie d'autonomie pour les étudiants",
    "categorie": "education",
    "sous_categorie": "etudiants",
    "public": ["jeunes"],
    "resume": "1063€ par mois pour tout étudiant détaché du foyer fiscal parental.",
    "explication": "Les étudiants reçoivent une garantie d'autonomie de 1063€ net par mois (seuil de pauvreté). Fin de la précarité étudiante et des petits boulots qui nuisent aux études.",
    "chiffre_cle": "23% des 18-24 ans vivent sous le seuil de pauvreté",
    "exemple_concret": "Un étudiant en master peut se concentrer sur ses études sans travailler 20h/semaine en livraison.",
    "financement": "Inclus dans le plan pauvreté",
    "url": "/2100/mesures/garantie-autonomie-etudiants.html",
    "motscles": ["étudiant", "précarité", "bourse", "autonomie", "seuil de pauvreté"],
    "statut": "mesure_cle"
  },

  // === LOGEMENT (5) ===
  {
    "id": 34,
    "titre": "200 000 logements publics par an",
    "categorie": "logement",
    "sous_categorie": "social",
    "public": ["tous", "precaires", "jeunes"],
    "resume": "Construction massive de logements publics : 200 000 par an pendant 5 ans.",
    "explication": "La construction de logements sociaux est relancée : 200 000 par an, dont 15 000 logements étudiants. Priorité aux normes écologiques (bâtiments à énergie positive).",
    "chiffre_cle": "2 millions de familles en attente d'un logement social",
    "exemple_concret": "Une famille de 4 personnes en attente depuis 3 ans se voit proposer un appartement neuf bien isolé.",
    "financement": "15 milliards d'euros sur le quinquennat",
    "url": "/2100/mesures/construction-logements-publics.html",
    "motscles": ["HLM", "logement social", "construction", "logement public", "bailleurs sociaux"],
    "statut": "mesure_cle"
  },
  {
    "id": 35,
    "titre": "Encadrement des loyers",
    "categorie": "logement",
    "sous_categorie": "location",
    "public": ["tous", "jeunes", "precaires"],
    "resume": "Encadrement des loyers partout, avec décote de 20% dans les zones très tendues.",
    "explication": "Les loyers sont encadrés sur tout le territoire. Dans les zones très tendues (Paris, Lyon, Bordeaux...), le loyer maximal est fixé à 20% en dessous du loyer médian.",
    "chiffre_cle": "Les loyers ont augmenté de 44% dans le privé en 10 ans",
    "exemple_concret": "À Paris, un 2 pièces loué 1200€ voit son loyer plafonné à 960€.",
    "financement": "Sans coût pour l'État - transfert des propriétaires vers les locataires",
    "url": "/2100/mesures/encadrement-loyers.html",
    "motscles": ["loyer", "encadrement", "location", "propriétaire", "locataire"],
    "statut": "mesure"
  },
  {
    "id": 36,
    "titre": "Interdiction des expulsions sans relogement",
    "categorie": "logement",
    "sous_categorie": "location",
    "public": ["precaires", "tous"],
    "resume": "Plus aucune expulsion locative sans proposition de relogement public.",
    "explication": "L'expulsion d'un locataire est interdite si l'État ne peut pas proposer une solution de relogement public (HLM, pension de famille, hébergement).",
    "chiffre_cle": "300 000 personnes sans domicile fixe en France",
    "exemple_concret": "Une famille avec 2 enfants ne peut pas être mise à la rue ; l'État doit leur trouver un logement de substitution.",
    "financement": "2 milliards d'euros par an",
    "url": "/2100/mesures/interdiction-expulsions.html",
    "motscles": ["expulsion", "relogement", "DALO", "sans-abri", "logement"],
    "statut": "mesure_cle"
  },
  {
    "id": 37,
    "titre": "Zéro sans-abri",
    "categorie": "logement",
    "sous_categorie": "social",
    "public": ["precaires"],
    "resume": "Plan d'urgence pour sortir 300 000 personnes de la rue et des hébergements d'urgence.",
    "explication": "Objectif 'zéro sans-abri' : réquisition des logements vacants, création de pensions de famille, logement d'abord pour tous.",
    "chiffre_cle": "3,1 millions de logements vacants en France",
    "exemple_concret": "Un SDF suivi par le 115 se voit proposer un logement, pas juste une nuit d'hôtel.",
    "financement": "3,7 milliards d'euros par an",
    "url": "/2100/mesures/zero-sans-abri.html",
    "motscles": ["SDF", "sans-abri", "rue", "hébergement d'urgence", "115"],
    "statut": "mesure_cle"
  },
  {
    "id": 38,
    "titre": "Rénovation obligatoire des passoires thermiques",
    "categorie": "logement",
    "sous_categorie": "renovation",
    "public": ["tous", "precaires"],
    "resume": "Les logements classés F et G ne peuvent plus être loués sans rénovation complète.",
    "explication": "Les passoires thermiques (étiquettes F et G du DPE) doivent être rénovées avant d'être remises en location. Aides de l'État pour les propriétaires modestes.",
    "chiffre_cle": "4,8 millions de logements sont des passoires thermiques",
    "exemple_concret": "Un propriétaire d'un appartement classé G doit l'isoler avant de pouvoir le relouer.",
    "financement": "Inclus dans le plan rénovation thermique",
    "url": "/2100/mesures/renovation-passoires-thermiques.html",
    "motscles": ["passoire thermique", "DPE", "rénovation", "isolation", "location"],
    "statut": "mesure"
  },

  // === DÉMOCRATIE & JUSTICE (6) ===
  {
    "id": 39,
    "titre": "6e République",
    "categorie": "democratie",
    "sous_categorie": "institutions",
    "public": ["tous"],
    "resume": "Convocation d'une Assemblée constituante pour écrire une nouvelle Constitution.",
    "explication": "Une Assemblée constituante, composée de citoyens élus et tirés au sort, rédige une nouvelle Constitution. Le projet est soumis à référendum. Fin de la monarchie présidentielle, régime parlementaire.",
    "chiffre_cle": "63% des Français soutiennent une nouvelle Constitution",
    "exemple_concret": "Les citoyens participent à l'écriture des règles du jeu démocratique via des cahiers de doléances.",
    "financement": "300 millions d'euros pour le référendum, 500 millions par an pour la Constituante",
    "url": "/2100/mesures/6e-republique.html",
    "motscles": ["6e République", "Constituante", "Constitution", "démocratie", "référendum"],
    "statut": "mesure_cle"
  },
  {
    "id": 40,
    "titre": "Référendum d'initiative citoyenne (RIC)",
    "categorie": "democratie",
    "sous_categorie": "institutions",
    "public": ["tous"],
    "resume": "Les citoyens peuvent proposer des lois, abroger des textes ou révoquer des élus.",
    "explication": "Le RIC permet à des citoyens réunissant suffisamment de signatures de : proposer une loi, abroger une loi existante, révoquer un élu en cours de mandat.",
    "chiffre_cle": "69% des Français soutiennent le RIC",
    "exemple_concret": "Les Gilets jaunes auraient pu proposer le RIC qu'ils réclamaient.",
    "financement": "Sans coût supplémentaire - organisation de référendums",
    "url": "/2100/mesures/ric.html",
    "motscles": ["RIC", "référendum", "initiative citoyenne", "révocation", "démocratie directe"],
    "statut": "mesure_cle"
  },
  {
    "id": 41,
    "titre": "Sortie de l'OTAN",
    "categorie": "international",
    "sous_categorie": "defense",
    "public": ["tous"],
    "resume": "Retrait de la France du commandement intégré de l'OTAN puis de l'organisation.",
    "explication": "La France quitte l'OTAN pour retrouver sa souveraineté militaire et diplomatique. Elle devient non-alignée, au service de la paix et du droit international.",
    "chiffre_cle": "96% des Français soutiennent le retrait de l'OTAN selon certains sondages",
    "exemple_concret": "La France n'est plus entraînée dans des guerres décidées par les États-Unis.",
    "financement": "Économies sur les contributions à l'OTAN",
    "url": "/2100/mesures/sortie-otan.html",
    "motscles": ["OTAN", "défense", "souveraineté", "non-alignement", "paix"],
    "statut": "mesure"
  },
  {
    "id": 42,
    "titre": "Proportionnelle aux législatives",
    "categorie": "democratie",
    "sous_categorie": "institutions",
    "public": ["tous"],
    "resume": "Élection des députés à la proportionnelle intégrale.",
    "explication": "Les élections législatives se font à la proportionnelle intégrale. Fin du scrutin majoritaire qui élimine les petites formations politiques.",
    "chiffre_cle": "68% des Français soutiennent la proportionnelle",
    "exemple_concret": "Un parti qui obtient 10% des voix a 10% des sièges à l'Assemblée.",
    "financement": "Sans coût - réorganisation des circonscriptions",
    "url": "/2100/mesures/proportionnelle-legislatives.html",
    "motscles": ["proportionnelle", "législatives", "députés", "scrutin", "Assemblée nationale"],
    "statut": "mesure"
  },
  {
    "id": 43,
    "titre": "Droit de vote à 16 ans",
    "categorie": "democratie",
    "sous_categorie": "institutions",
    "public": ["jeunes"],
    "resume": "Le droit de vote est accordé à partir de 16 ans.",
    "explication": "Les jeunes de 16 et 17 ans peuvent voter à toutes les élections. Ils sont déjà imposables, peuvent travailler, être émancipés. Cette mesure élargit le corps électoral de 1,5 million de personnes.",
    "chiffre_cle": "87% d'abstention chez les 18-24 ans (fatigue démocratique précoce)",
    "exemple_concret": "Un lycéen de 17 ans vote pour la première fois à la présidentielle.",
    "financement": "Sans coût - mise à jour des listes électorales",
    "url": "/2100/mesures/droit-vote-16-ans.html",
    "motscles": ["vote", "16 ans", "jeunes", "élections", "citoyenneté"],
    "statut": "mesure"
  },
  {
    "id": 44,
    "titre": "Fin de l'état d'urgence permanent",
    "categorie": "democratie",
    "sous_categorie": "liberte",
    "public": ["tous"],
    "resume": "Abrogation de l'état d'urgence sanitaire et sécuritaire, retour au droit commun.",
    "explication": "Fin des états d'urgence qui se sont installés dans la durée. Abrogation des lois liberticides (SILT, sécurité globale, loi renseignement). Retour aux garanties démocratiques normales.",
    "chiffre_cle": "24 lois liberticides adoptées entre 2017 et 2024",
    "exemple_concret": "Fin des contrôles d'identité abusifs sans motif, fin du pass sanitaire.",
    "financement": "Sans coût",
    "url": "/2100/mesures/fin-etat-urgence.html",
    "motscles": ["état d'urgence", "libertés", "sécurité globale", "renseignement", "pass sanitaire"],
    "statut": "mesure"
  },

  // === FISCALITÉ (6 - complétée) ===
  {
    "id": 45,
    "titre": "Rétablissement de l'ISF",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["riches"],
    "resume": "Rétablissement de l'Impôt de Solidarité sur la Fortune (ISF).",
    "explication": "L'ISF supprimé par Macron est rétabli avec un barème progressif. Il rapporte 10 milliards d'euros par an.",
    "chiffre_cle": "78% des Français soutiennent le rétablissement de l'ISF",
    "exemple_concret": "Une personne avec 2 millions d'euros de patrimoine paie à nouveau l'ISF.",
    "financement": "10 milliards d'euros par an",
    "url": "/2100/mesures/retablissement-isf.html",
    "motscles": ["ISF", "impôt", "fortune", "riches", "patrimoine"],
    "statut": "mesure_cle"
  },
  {
    "id": 46,
    "titre": "Impôt sur le revenu à 14 tranches",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["tous"],
    "resume": "Barème de l'impôt sur le revenu élargi à 14 tranches (comme en 1983).",
    "explication": "L'impôt sur le revenu redevient fortement progressif : 14 tranches contre 5 actuellement. Taux marginal à 90% pour les revenus > 400 000€/an. Baisse d'impôt pour les revenus < 4000€/mois.",
    "chiffre_cle": "Les 10% les plus riches paient proportionnellement moins d'impôts que les 10% les plus pauvres",
    "exemple_concret": "Un smicard ne paie plus d'impôt sur le revenu.",
    "financement": "5 milliards d'euros de recettes supplémentaires par an",
    "url": "/2100/mesures/impot-revenu-14-tranches.html",
    "motscles": ["impôt sur le revenu", "progressivité", "tranches", "barème", "IR"],
    "statut": "mesure_cle"
  },
  {
    "id": 47,
    "titre": "Suppression de la flat tax",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["riches"],
    "resume": "Suppression de la flat tax (PFU) sur les revenus du capital.",
    "explication": "La flat tax à 30% sur les revenus du capital (dividendes, plus-values) est supprimée. Les revenus du capital sont imposés comme ceux du travail, avec le barème progressif de l'IR.",
    "chiffre_cle": "La flat tax a coûté 3,5 milliards par an aux finances publiques",
    "exemple_concret": "Un rentier qui vit de ses dividendes paie désormais l'impôt comme un salarié.",
    "financement": "1,8 milliard d'euros par an",
    "url": "/2100/mesures/suppression-flat-tax.html",
    "motscles": ["flat tax", "PFU", "capital", "dividendes", "plus-values"],
    "statut": "mesure"
  },
  {
    "id": 48,
    "titre": "Héritage maximum à 12 millions d'euros",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["riches"],
    "resume": "Plafonnement de l'héritage à 12 millions d'euros par personne.",
    "explication": "Au-delà de 12 millions d'euros d'héritage (100 fois le patrimoine médian), tout est reversé à l'État pour financer la garantie d'autonomie des jeunes.",
    "chiffre_cle": "Le top 0,1% des héritiers reçoit 180 fois l'héritage médian",
    "exemple_concret": "Un héritier qui reçoit 15 millions d'euros garde 12 millions, les 3 millions vont à l'État.",
    "financement": "17 milliards d'euros par an",
    "url": "/2100/mesures/heritage-maximum.html",
    "motscles": ["héritage", "succession", "donation", "transmission", "patrimoine"],
    "statut": "mesure"
  },
  {
    "id": 49,
    "titre": "Taxe sur les superprofits",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["entreprises"],
    "resume": "Taxe exceptionnelle de 50% sur les superprofits des grandes entreprises.",
    "explication": "Les entreprises réalisant des bénéfices exceptionnels (par rapport à la moyenne des 5 années précédentes) paient une taxe de 50% sur ces superprofits.",
    "chiffre_cle": "TotalEnergies a réalisé 36 milliards de bénéfices en 2022",
    "exemple_concret": "Une entreprise qui double ses bénéfices paie 50% sur la moitié excédentaire.",
    "financement": "Recette ponctuelle non chiffrée",
    "url": "/2100/mesures/taxe-superprofits.html",
    "motscles": ["superprofit", "taxe", "entreprise", "bénéfice", "crise"],
    "statut": "mesure"
  },
  {
    "id": 50,
    "titre": "Impôt universel sur les multinationales",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["entreprises"],
    "resume": "Les multinationales paient l'impôt sur les sociétés en fonction de leur activité en France.",
    "explication": "Les multinationales sont taxées sur la part de leur activité réalisée en France, où qu'elles soient domiciliées. Fin de l'optimisation fiscale via l'Irlande, le Luxembourg ou les paradis fiscaux.",
    "chiffre_cle": "26 milliards d'euros d'évasion fiscale par an",
    "exemple_concret": "Google paie l'IS sur les 10% de ses ventes mondiales réalisées en France.",
    "financement": "26 milliards d'euros par an",
    "url": "/2100/mesures/impot-universel-multinationales.html",
    "motscles": ["multinationales", "évasion fiscale", "impôt sur les sociétés", "GAFA", "paradis fiscaux"],
    "statut": "mesure_cle"
  }

    // === ÉCOLOGIE & CLIMAT (50 mesures - Lot 2) ===
  {
    "id": 51,
    "titre": "Sortie du nucléaire programmée",
    "categorie": "ecologie",
    "sous_categorie": "energie",
    "public": ["tous"],
    "resume": "Fermeture progressive de tous les réacteurs nucléaires d'ici 2050, début du démantèlement dès 2023.",
    "explication": "La France sort du nucléaire. Les centrales les plus anciennes (Fessenheim, Bugey, Tricastin) ferment en priorité. Un plan de reconversion est prévu pour les 200 000 salariés de la filière.",
    "chiffre_cle": "56 réacteurs nucléaires en France, 2/3 dépasseront 40 ans en 2030",
    "exemple_concret": "La centrale de Fessenheim ferme en 2023, les salariés sont reclassés dans les énergies renouvelables.",
    "financement": "Économies : 10 milliards/an d'ici 2035 (fin du Grand Carénage)",
    "motscles": ["nucléaire", "sortie", "centrale", "Fessenheim", "démantèlement"],
    "statut": "mesure_cle"
  },
  {
    "id": 52,
    "titre": "Interdiction des néonicotinoïdes",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Interdiction définitive de tous les néonicotinoïdes, tueurs d'abeilles et toxiques pour la biodiversité.",
    "explication": "Les néonicotinoïdes, pesticides tueurs d'abeilles, sont définitivement interdits. Aucune dérogation possible. Les agriculteurs sont accompagnés vers des alternatives.",
    "chiffre_cle": "30% des colonies d'abeilles disparaissent chaque année en France",
    "exemple_concret": "Un agriculteur utilisant des semences enrobées de néonicotinoïdes doit passer à des méthodes de biocontrôle.",
    "financement": "Aides à la conversion pour les agriculteurs",
    "motscles": ["néonicotinoïdes", "abeilles", "pesticides", "insecticides", "biodiversité"],
    "statut": "mesure_cle"
  },
  {
    "id": 53,
    "titre": "Plan vélo : 10 milliards sur 5 ans",
    "categorie": "ecologie",
    "sous_categorie": "transports",
    "public": ["tous", "jeunes"],
    "resume": "10 milliards d'euros pour développer les pistes cyclables, le stationnement sécurisé et l'apprentissage du vélo.",
    "explication": "Un plan national vélo est lancé : 10 milliards sur 5 ans pour doubler le réseau de pistes cyclables, créer 500 000 places de stationnement sécurisé en gare, et financer l'apprentissage du vélo à l'école.",
    "chiffre_cle": "1/3 des actifs habitent à moins de 5 km de leur travail",
    "exemple_concret": "Un couloir de bus devient une piste cyclable protégée, reliant la banlieue au centre-ville.",
    "financement": "10 milliards sur 5 ans, dont 50% pour l'État, 50% pour les collectivités",
    "motscles": ["vélo", "cyclable", "piste", "stationnement", "mobilité douce"],
    "statut": "mesure"
  },
  {
    "id": 54,
    "titre": "Interdiction des chasses traditionnelles cruelles",
    "categorie": "ecologie",
    "sous_categorie": "biodiversite",
    "public": ["tous"],
    "resume": "Interdiction de la chasse à courre, de la vénerie sous terre, des chasses à la glu et des pièges mutilants.",
    "explication": "Les pratiques de chasse cruelles sont interdites : chasse à courre (le sanglier, le cerf et le renard), vénerie sous terre (déterrage des blaireaux et renards), chasse à la glu, pièges mutilants.",
    "chiffre_cle": "84% des Français sont opposés à la chasse à courre",
    "exemple_concret": "Le sanglier ne peut plus être traqué pendant des heures avant d'être achevé par une meute.",
    "financement": "Sans coût - simple changement réglementaire",
    "motscles": ["chasse", "courre", "vénerie", "glu", "piège", "bien-être animal"],
    "statut": "mesure"
  },
  {
    "id": 55,
    "titre": "Zéro déchet plastique en mer Méditerranée",
    "categorie": "ecologie",
    "sous_categorie": "mer",
    "public": ["tous"],
    "resume": "Plan d'action avec les pays riverains pour éliminer les déchets plastiques en Méditerranée d'ici 2030.",
    "explication": "La France coordonne un plan d'action avec l'Espagne, l'Italie, la Grèce et les pays du Maghreb pour éliminer les déchets plastiques en Méditerranée. Objectif : zéro plastique flottant en 2030.",
    "chiffre_cle": "D'ici 2050, il y aura plus de plastique que de poissons en Méditerranée",
    "exemple_concret": "Une bouteille en plastique jetée à Marseille ne finit plus sur les plages de Tunisie.",
    "financement": "500 millions d'euros de fonds européens et nationaux",
    "motscles": ["Méditerranée", "plastique", "pollution", "déchets", "océan"],
    "statut": "mesure"
  },
  {
    "id": 56,
    "titre": "Moratoire sur les méga-bassines",
    "categorie": "ecologie",
    "sous_categorie": "eau",
    "public": ["agriculteurs", "tous"],
    "resume": "Suspension de tous les projets de méga-bassines pour stockage d'eau agricole.",
    "explication": "Les projets de méga-bassines (rétentions d'eau pour l'irrigation agricole) sont suspendus. Une concertation est ouverte pour définir un nouveau partage de l'eau entre usages.",
    "chiffre_cle": "Les méga-bassines de Sainte-Soline (79) ont provoqué des manifestations massives en 2022-2023",
    "exemple_concret": "Le projet de bassine de 650 000 m³ dans les Deux-Sèvres est annulé.",
    "financement": "Sans coût - suspension des projets",
    "motscles": ["méga-bassine", "eau", "irrigation", "agriculture", "retenue"],
    "statut": "mesure"
  },
  {
    "id": 57,
    "titre": "Plan de dépollution des sols industriels",
    "categorie": "ecologie",
    "sous_categorie": "pollution",
    "public": ["tous"],
    "resume": "Dépollution des 500 sites industriels les plus contaminés en France d'ici 2030.",
    "explication": "Un plan national de dépollution est lancé pour traiter les friches industrielles contaminées (métaux lourds, solvants, hydrocarbures). Priorité aux sites à proximité des habitations.",
    "chiffre_cle": "Entre 300 000 et 500 000 sites potentiellement pollués en France",
    "exemple_concret": "L'ancienne fonderie de Métaleurop à Noyelles-Godault est dépolluée et transformée en zone naturelle.",
    "financement": "2 milliards d'euros sur le quinquennat",
    "motscles": ["dépollution", "sols", "friche", "industriel", "pollution"],
    "statut": "mesure"
  },
  {
    "id": 58,
    "titre": "Interdiction des SUV en centre-ville",
    "categorie": "ecologie",
    "sous_categorie": "transports",
    "public": ["tous"],
    "resume": "Interdiction de circulation des SUV dans les centres-villes des métropoles d'ici 2026.",
    "explication": "Les SUV (véhicules de plus de 1,8 tonne) sont interdits dans les centres-villes de Paris, Lyon, Marseille, Bordeaux, Lille, Toulouse et Nice. Une vignette critique'air est renforcée.",
    "chiffre_cle": "Les SUV émettent 20% de CO2 en plus qu'une citadine",
    "exemple_concret": "Un propriétaire de Range Rover ne peut plus entrer dans Paris intra-muros.",
    "financement": "Sans coût - réglementation",
    "motscles": ["SUV", "centre-ville", "pollution", "crit'air", "voiture"],
    "statut": "mesure"
  },
  {
    "id": 59,
    "titre": "Reconstitution des haies bocagères",
    "categorie": "ecologie",
    "sous_categorie": "biodiversite",
    "public": ["agriculteurs"],
    "resume": "Plantation de 100 000 km de haies bocagères d'ici 2030 pour restaurer la biodiversité.",
    "explication": "Un plan national de plantation de haies est lancé : 100 000 km de haies (l'équivalent du réseau de l'époque des remembrements) sont replantés chez les agriculteurs volontaires.",
    "chiffre_cle": "70% des haies ont disparu en France depuis 1950",
    "exemple_concret": "Un éleveur de bovins replante 2 km de haies autour de ses prairies, favorisant la biodiversité et protégeant ses bêtes du vent.",
    "financement": "1 milliard d'euros d'aides aux agriculteurs",
    "motscles": ["haie", "bocage", "biodiversité", "remembrement", "agriculture"],
    "statut": "mesure"
  },
  {
    "id": 60,
    "titre": "Fin des subventions aux énergies fossiles",
    "categorie": "ecologie",
    "sous_categorie": "energie",
    "public": ["entreprises"],
    "resume": "Suppression de toutes les subventions directes et indirectes aux énergies fossiles.",
    "explication": "Toutes les aides publiques aux énergies fossiles (charbon, pétrole, gaz) sont supprimées : niches fiscales, subventions à l'export, aides à la recherche. L'argent est réorienté vers les énergies renouvelables.",
    "chiffre_cle": "10 milliards d'euros de subventions aux énergies fossiles chaque année",
    "exemple_concret": "TotalEnergies ne reçoit plus d'aide publique pour ses forages.",
    "financement": "10 milliards d'euros d'économies par an",
    "motscles": ["subventions", "énergies fossiles", "pétrole", "gaz", "charbon"],
    "statut": "mesure_cle"
  },
  {
    "id": 61,
    "titre": "Protection des zones humides",
    "categorie": "ecologie",
    "sous_categorie": "eau",
    "public": ["tous"],
    "resume": "Interdiction de tout assèchement ou construction sur les zones humides classées.",
    "explication": "Les zones humides (marais, tourbières, prairies humides) sont sanctuarisées. Aucun drainage, remblaiement ou construction n'est autorisé. Les zones déjà dégradées sont restaurées.",
    "chiffre_cle": "50% des zones humides ont disparu en France depuis 1960",
    "exemple_concret": "Un promoteur immobilier ne peut plus construire sur un marais asséché.",
    "financement": "500 millions pour la restauration",
    "motscles": ["zone humide", "marais", "tourbière", "biodiversité", "eau"],
    "statut": "mesure"
  },
  {
    "id": 62,
    "titre": "Création d'un pôle public de l'eau",
    "categorie": "ecologie",
    "sous_categorie": "eau",
    "public": ["tous"],
    "resume": "Retour de la gestion de l'eau en régie publique, fin des délégations à Veolia et Suez.",
    "explication": "L'eau redevient un bien commun géré par des régies publiques. Les contrats avec Veolia et Suez ne sont pas renouvelés. Les usagers participent à la gouvernance via des comités citoyens.",
    "chiffre_cle": "43% des Français sont encore gérés par des opérateurs privés",
    "exemple_concret": "Les habitants de Bordeaux décident collectivement des investissements sur leur réseau d'eau.",
    "financement": "Gain : 25% d'économies par rapport aux délégations privées",
    "motscles": ["eau", "régie publique", "Veolia", "Suez", "bien commun"],
    "statut": "mesure_cle"
  },
  {
    "id": 63,
    "titre": "Plan de rénovation des écoles",
    "categorie": "ecologie",
    "sous_categorie": "batiment",
    "public": ["tous", "jeunes"],
    "resume": "Rénovation énergétique et désamiantage de toutes les écoles publiques d'ici 2030.",
    "explication": "Un plan national de rénovation des écoles est lancé : isolation, désamiantage, installation de capteurs CO2, végétalisation des cours. Priorité aux écoles en REP et en zones rurales.",
    "chiffre_cle": "50% des écoles ont été construites avant 1975",
    "exemple_concret": "Une école maternelle du 93 est désamiantée et ses fenêtres sont remplacées.",
    "financement": "5 milliards d'euros sur le quinquennat",
    "motscles": ["école", "rénovation", "désamiantage", "isolation", "bâtiment scolaire"],
    "statut": "mesure"
  },
  {
    "id": 64,
    "titre": "Interdiction des pesticides à proximité des écoles",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Interdiction de tout épandage de pesticides dans un rayon de 200 mètres autour des écoles et hôpitaux.",
    "explication": "Les zones de non-traitement (ZNT) sont étendues à 200 mètres autour des établissements scolaires, crèches et hôpitaux (contre 10 mètres actuellement).",
    "chiffre_cle": "Plusieurs études montrent une sur-incidence de cancers chez les enfants vivant près des champs",
    "exemple_concret": "Une école située à côté d'un vignoble n'est plus exposée aux pulvérisations.",
    "financement": "Sans coût - réglementation",
    "motscles": ["pesticides", "école", "hôpital", "épandage", "ZNT"],
    "statut": "mesure_cle"
  },
  {
    "id": 65,
    "titre": "Création d'un fonds d'indemnisation des victimes de pesticides",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["agriculteurs", "ruraux"],
    "resume": "Fonds public pour indemniser les agriculteurs et riverains victimes de maladies liées aux pesticides.",
    "explication": "Un fonds d'indemnisation est créé pour les agriculteurs et riverains atteints de maladies reconnues liées aux pesticides (maladie de Parkinson, cancers, etc.). La présomption est inversée : c'est à l'industriel de prouver l'absence de lien.",
    "chiffre_cle": "Un agriculteur sur deux déclare avoir eu des problèmes de santé liés aux pesticides",
    "exemple_concret": "Un viticulteur atteint de Parkinson reçoit une indemnité sans avoir à prouver le lien.",
    "financement": "500 millions d'euros abondés par les fabricants de pesticides",
    "motscles": ["pesticides", "indemnisation", "Parkinson", "agriculteur", "santé"],
    "statut": "mesure"
  },
  {
    "id": 66,
    "titre": "Gratuité des transports en commun pour les moins de 25 ans",
    "categorie": "ecologie",
    "sous_categorie": "transports",
    "public": ["jeunes"],
    "resume": "Transports en commun gratuits pour tous les moins de 25 ans dans toutes les agglomérations.",
    "explication": "Les moins de 25 ans bénéficient de la gratuité des bus, métros, trams et TER. Cette mesure encourage l'usage des transports collectifs et soulage le budget des jeunes.",
    "chiffre_cle": "Déjà appliqué à Dunkerque, Montpellier et dans 30 villes moyennes",
    "exemple_concret": "Un étudiant de 20 ans peut prendre le bus gratuitement pour aller en cours.",
    "financement": "1,5 milliard d'euros par an, compensé aux collectivités par l'État",
    "motscles": ["transport gratuit", "jeunes", "bus", "métro", "TER"],
    "statut": "mesure"
  },
  {
    "id": 67,
    "titre": "Plan de verdissement des villes",
    "categorie": "ecologie",
    "sous_categorie": "urbanisme",
    "public": ["tous"],
    "resume": "Plantation d'un million d'arbres en ville et désimperméabilisation des cours d'école.",
    "explication": "Un plan national de verdissement urbain est lancé : 1 million d'arbres plantés, désimperméabilisation des 50 000 cours d'école (végétalisation), création de forêts urbaines.",
    "chiffre_cle": "Une cour d'école végétalisée est 10°C plus fraîche en été",
    "exemple_concret": "La cour en bitume d'une école parisienne devient un jardin avec des arbres et des potagers.",
    "financement": "2 milliards d'euros pour les communes",
    "motscles": ["végétalisation", "arbre", "cour d'école", "îlot de fraîcheur", "urbanisme"],
    "statut": "mesure"
  },
  {
    "id": 68,
    "titre": "Interdiction des vols privés (jets)",
    "categorie": "ecologie",
    "sous_categorie": "transports",
    "public": ["riches"],
    "resume": "Interdiction des jets privés pour les vols de moins de 1000 km.",
    "explication": "Les jets privés sont interdits pour les trajets de moins de 1000 km (Paris-Nice, Paris-Genève, etc.). Les déplacements doivent se faire en train ou en avion commercial.",
    "chiffre_cle": "Un jet privé pollue 10 fois plus par passager qu'un vol commercial",
    "exemple_concret": "Un milliardaire ne peut plus prendre son jet pour aller de Paris à Saint-Tropez.",
    "financement": "Sans coût - réglementation",
    "motscles": ["jet privé", "aviation", "luxe", "pollution", "climat"],
    "statut": "mesure"
  },
  {
    "id": 69,
    "titre": "Plan de sortie des PFAS (polluants éternels)",
    "categorie": "ecologie",
    "sous_categorie": "pollution",
    "public": ["tous"],
    "resume": "Interdiction progressive des PFAS (polluants éternels) d'ici 2030, dépollution des sites contaminés.",
    "explication": "Les PFAS (substances per- et polyfluoroalkylées), utilisés dans les poêles antiadhésives, les vêtements imperméables et les mousses anti-incendie, sont interdits progressivement. Les sites industriels contaminés sont dépollués.",
    "chiffre_cle": "Les PFAS sont présents dans le sang de 100% des Français",
    "exemple_concret": "Une usine chimique du Rhône doit traiter ses rejets de PFAS.",
    "financement": "1 milliard d'euros pour la dépollution, payé par les industriels",
    "motscles": ["PFAS", "polluant éternel", "Teflon", "dépollution", "chimique"],
    "statut": "mesure"
  },
  {
    "id": 70,
    "titre": "Création de 10 parcs nationaux supplémentaires",
    "categorie": "ecologie",
    "sous_categorie": "biodiversite",
    "public": ["tous"],
    "resume": "Création de 10 nouveaux parcs nationaux d'ici 2030 pour protéger 30% du territoire.",
    "explication": "10 nouveaux parcs nationaux sont créés, dont 5 en métropole (forêt de Chaux, Morvan, Ardèche, etc.) et 5 en Outre-mer. Objectif : passer de 20% à 30% de territoire protégé.",
    "chiffre_cle": "La France a 11 parcs nationaux, contre 63 aux États-Unis",
    "exemple_concret": "Le massif de la Chartreuse devient un parc national, interdisant les nouvelles constructions.",
    "financement": "200 millions d'euros par an pour les parcs",
    "motscles": ["parc national", "protection", "biodiversité", "réserve", "nature"],
    "statut": "mesure"
  },
  {
    "id": 71,
    "titre": "Interdiction de l'élevage en cage",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["agriculteurs"],
    "resume": "Interdiction de tous les élevages en cage (poules, lapins, porcs, veaux) d'ici 2027.",
    "explication": "Les élevages en cage sont interdits : poules pondeuses, lapins, truies gestantes, veaux. L'élevage doit être en plein air ou en bâtiment avec accès à l'extérieur.",
    "chiffre_cle": "60% des poules pondeuses sont encore en cage",
    "exemple_concret": "Un éleveur de poules pondeuses passe de cages à un élevage en plein air.",
    "financement": "Aides à la conversion pour les éleveurs",
    "motscles": ["élevage", "cage", "bien-être animal", "poule", "lapin"],
    "statut": "mesure"
  },
  {
    "id": 72,
    "titre": "Plan de lutte contre l'orpaillage illégal en Guyane",
    "categorie": "ecologie",
    "sous_categorie": "outre-mer",
    "public": ["guyanais"],
    "resume": "Moyens renforcés pour lutter contre l'orpaillage illégal et la pollution au mercure en Guyane.",
    "explication": "Les moyens militaires et douaniers sont renforcés pour lutter contre l'orpaillage illégal en forêt guyanaise. La pollution au mercure est dépolluée. Les populations amérindiennes sont protégées.",
    "chiffre_cle": "10 tonnes de mercure rejetées chaque année en Guyane par l'orpaillage illégal",
    "exemple_concret": "Une opération militaire détruit 50 puits clandestins sur le fleuve Maroni.",
    "financement": "100 millions d'euros pour les moyens de lutte",
    "motscles": ["Guyane", "orpaillage", "mercure", "illégal", "amérindien"],
    "statut": "mesure"
  },
  {
    "id": 73,
    "titre": "Interdiction des feux d'artifice et lanternes",
    "categorie": "ecologie",
    "sous_categorie": "pollution",
    "public": ["tous"],
    "resume": "Interdiction des feux d'artifice et lâchers de lanternes pour protéger la faune et limiter la pollution.",
    "explication": "Les feux d'artifice privés et les lâchers de lanternes sont interdits. Les feux d'artifice publics sont strictement encadrés (dates limitées, pas de métaux lourds).",
    "chiffre_cle": "Un feu d'artifice émet autant de particules fines qu'une voiture roulant 5000 km",
    "exemple_concret": "Le 14 juillet, les feux d'artifice utilisent des poudres sans perchlorate.",
    "financement": "Sans coût - réglementation",
    "motscles": ["feu d'artifice", "lanterne", "pollution", "faune", "bruit"],
    "statut": "mesure"
  },
  {
    "id": 74,
    "titre": "Plan de recyclage des déchets électroniques",
    "categorie": "ecologie",
    "sous_categorie": "dechets",
    "public": ["tous"],
    "resume": "Objectif 90% de recyclage des déchets électroniques d'ici 2030, création de filières locales.",
    "explication": "Un plan national de recyclage des DEEE (déchets d'équipements électriques et électroniques) est lancé. Objectif : 90% de recyclage d'ici 2030. Création de filières locales pour récupérer les métaux rares.",
    "chiffre_cle": "Seulement 40% des déchets électroniques sont recyclés en France",
    "exemple_concret": "Un smartphone usagé est démonté et ses composants réutilisés pour fabriquer de nouveaux appareils.",
    "financement": "500 millions d'euros pour structurer la filière",
    "motscles": ["déchet électronique", "recyclage", "métaux rares", "smartphone", "DEEE"],
    "statut": "mesure"
  },
  {
    "id": 75,
    "titre": "Interdiction de la publicité pour les produits polluants",
    "categorie": "ecologie",
    "sous_categorie": "consommation",
    "public": ["tous"],
    "resume": "Interdiction de la publicité pour les SUV, les vols intérieurs, les produits en plastique à usage unique.",
    "explication": "La publicité pour les produits les plus polluants est interdite : SUV, vols intérieurs, plastiques à usage unique, viande issue d'élevage intensif, pesticides.",
    "chiffre_cle": "La publicité augmente la consommation de 20 à 40%",
    "exemple_concret": "Plus de pub à la télé pour le dernier SUV Mercedes.",
    "financement": "Sans coût - réglementation",
    "motscles": ["publicité", "pollution", "SUV", "avion", "plastique"],
    "statut": "mesure"
  },
  {
    "id": 76,
    "titre": "Plan d'adaptation des littoraux à la montée des eaux",
    "categorie": "ecologie",
    "sous_categorie": "climat",
    "public": ["littoraux"],
    "resume": "Plan national pour relocaliser les habitations menacées par la montée des eaux d'ici 2050.",
    "explication": "Un plan d'adaptation des littoraux est lancé : cartographie des zones menacées, interdiction de construire dans les zones à risque, accompagnement des communes pour la relocalisation progressive des habitations.",
    "chiffre_cle": "La mer pourrait monter de 1 mètre d'ici 2100",
    "exemple_concret": "Le village de l'Aiguillon-sur-Mer (Vendée) est progressivement déplacé vers l'intérieur des terres.",
    "financement": "5 milliards d'euros sur 10 ans",
    "motscles": ["littoral", "montée des eaux", "relocalisation", "climat", "érosion"],
    "statut": "mesure"
  },
  {
    "id": 77,
    "titre": "Interdiction des expériences sur les animaux pour les cosmétiques",
    "categorie": "ecologie",
    "sous_categorie": "condition_animale",
    "public": ["tous"],
    "resume": "Renforcement de l'interdiction des tests sur les animaux pour les cosmétiques et les produits ménagers.",
    "explication": "L'interdiction des tests sur les animaux est renforcée et étendue aux produits ménagers. Les laboratoires doivent utiliser des méthodes substitutives (peau reconstruite, cellules souches).",
    "chiffre_cle": "L'UE a interdit les tests cosmétiques sur animaux en 2013, mais des contournements existent",
    "exemple_concret": "Un laboratoire de cosmétiques utilise de la peau reconstruite in vitro.",
    "financement": "Recherche sur les méthodes alternatives : 50 millions d'euros",
    "motscles": ["expérimentation animale", "cosmétique", "bien-être animal", "tests", "alternatives"],
    "statut": "mesure"
  },
  {
    "id": 78,
    "titre": "Plan de réduction des émissions de méthane",
    "categorie": "ecologie",
    "sous_categorie": "climat",
    "public": ["agriculteurs"],
    "resume": "Objectif -50% d'émissions de méthane d'ici 2030 (élevage, déchets, gaz).",
    "explication": "Un plan national de réduction des émissions de méthane est lancé : réduction de l'élevage bovin, captage du méthane dans les décharges, réparation des fuites sur le réseau gazier.",
    "chiffre_cle": "Le méthane a un pouvoir réchauffant 80 fois supérieur au CO2 sur 20 ans",
    "exemple_concret": "Un éleveur réduit son cheptel et plante des légumineuses pour l'alimentation animale.",
    "financement": "1 milliard d'euros d'aides à la conversion",
    "motscles": ["méthane", "élevage", "décharge", "gaz", "climat"],
    "statut": "mesure"
  },
  {
    "id": 79,
    "titre": "Création d'un corps de gardes-nature",
    "categorie": "ecologie",
    "sous_categorie": "biodiversite",
    "public": ["tous"],
    "resume": "Recrutement de 5000 gardes-nature pour surveiller et protéger les espaces naturels.",
    "explication": "Un corps de gardes-nature (police de l'environnement) est créé, avec 5000 recrutements. Ils sont chargés de faire respecter les réglementations environnementales (chasse, pêche, pollution, décharges sauvages).",
    "chiffre_cle": "Actuellement, 1 agent de l'OFB pour 1000 km²",
    "exemple_concret": "Un garde-nature verbalise un promeneur qui dérange une espèce protégée.",
    "financement": "300 millions d'euros par an",
    "motscles": ["garde-nature", "police", "environnement", "OFB", "surveillance"],
    "statut": "mesure"
  },
  {
    "id": 80,
    "titre": "Interdiction des OGM en plein champ",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Interdiction de toute culture d'OGM en plein champ, y compris les nouvelles techniques génomiques.",
    "explication": "Toute culture d'OGM en plein champ est interdite. Les NBT (nouvelles techniques génomiques, type CRISPR-Cas9) sont assimilées aux OGM et également interdites. La recherche en laboratoire reste autorisée.",
    "chiffre_cle": "Aucune culture d'OGM en France depuis 2008",
    "exemple_concret": "Un agriculteur ne peut pas planter du maïs OGM modifié par CRISPR.",
    "financement": "Sans coût - réglementation",
    "motscles": ["OGM", "NBT", "CRISPR", "transgénique", "plein champ"],
    "statut": "mesure"
  },
  {
    "id": 81,
    "titre": "Plan de gestion des eaux pluviales en ville",
    "categorie": "ecologie",
    "sous_categorie": "eau",
    "public": ["tous"],
    "resume": "Obligation de désimperméabiliser 20% des surfaces imperméables dans les villes d'ici 2030.",
    "explication": "Les villes doivent désimperméabiliser leurs sols (parkings, cours d'école, places publiques) pour permettre l'infiltration des eaux pluviales. Objectif : 20% de désimperméabilisation d'ici 2030.",
    "chiffre_cle": "Les sols artificialisés augmentent le risque d'inondation de 30%",
    "exemple_concret": "Un parking bitumé devient un jardin de pluie avec des arbres et des bassins.",
    "financement": "1 milliard d'euros d'aides aux communes",
    "motscles": ["eau pluviale", "désimperméabilisation", "inondation", "ville", "ruissellement"],
    "statut": "mesure"
  },
  {
    "id": 82,
    "titre": "Interdiction des gobelets et couverts plastiques",
    "categorie": "ecologie",
    "sous_categorie": "dechets",
    "public": ["tous"],
    "resume": "Interdiction de tous les gobelets, couverts, pailles et assiettes en plastique, même biodégradables.",
    "explication": "Les gobelets, couverts, pailles, assiettes et touillettes en plastique sont interdits, y compris les plastiques dits 'biodégradables' (souvent des leurres). Les alternatives réutilisables sont obligatoires.",
    "chiffre_cle": "5 milliards de gobelets plastiques jetés chaque année en France",
    "exemple_concret": "Un festival utilise des gobelets consignés en verre ou des tasses réutilisables.",
    "financement": "Sans coût - réglementation",
    "motscles": ["gobelet", "couverts", "paille", "plastique", "jetable"],
    "statut": "mesure"
  },
  {
    "id": 83,
    "titre": "Plan de protection des récifs coralliens",
    "categorie": "ecologie",
    "sous_categorie": "mer",
    "public": ["tous"],
    "resume": "Protection renforcée des récifs coralliens d'Outre-mer (Nouvelle-Calédonie, Mayotte, Polynésie).",
    "explication": "Les récifs coralliens des Outre-mer sont sanctuarisés : interdiction de la pêche destructrice, limitation de la fréquentation touristique, lutte contre le blanchissement via la réduction des pollutions locales.",
    "chiffre_cle": "Les récifs coralliens abritent 25% de la biodiversité marine",
    "exemple_concret": "Le lagon de Nouvelle-Calédonie devient une zone de protection intégrale.",
    "financement": "100 millions d'euros pour la recherche et la protection",
    "motscles": ["corail", "récif", "Outre-mer", "Nouvelle-Calédonie", "blanchissement"],
    "statut": "mesure"
  },
  {
    "id": 84,
    "titre": "Bonus-malus écologique sur les produits importés",
    "categorie": "ecologie",
    "sous_categorie": "commerce",
    "public": ["tous"],
    "resume": "Bonus-malus écologique sur les produits importés en fonction de leur empreinte carbone.",
    "explication": "Les produits importés sont taxés selon leur empreinte carbone (transport + production). Un bonus est accordé aux produits à faible empreinte (circuits courts, fabrication locale).",
    "chiffre_cle": "Les émissions importées dépassent les émissions nationales",
    "exemple_concret": "Une tomate importée du Maroc en hiver est taxée, pas une tomate de saison française.",
    "financement": "Recettes : 3,5 milliards d'euros par an",
    "motscles": ["bonus-malus", "importation", "carbone", "taxe", "circuit court"],
    "statut": "mesure_cle"
  },
  {
    "id": 85,
    "titre": "Plan de réduction des nitrates agricoles",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["agriculteurs"],
    "resume": "Réduction de 50% des nitrates dans les eaux souterraines d'ici 2030.",
    "explication": "Un plan de réduction des nitrates est lancé : limitation des épandages, zones tampons, conversion à l'agriculture biologique. Objectif : 50% de réduction des nitrates dans les eaux d'ici 2030.",
    "chiffre_cle": "1 Français sur 4 boit une eau contaminée aux nitrates",
    "exemple_concret": "Un éleveur de porcs réduit sa densité animale pour limiter les lisiers.",
    "financement": "500 millions d'euros d'aides",
    "motscles": ["nitrates", "eau", "pollution", "algues vertes", "agriculture"],
    "statut": "mesure"
  },
  {
    "id": 86,
    "titre": "Interdiction des terrasses chauffées",
    "categorie": "ecologie",
    "sous_categorie": "energie",
    "public": ["commercants"],
    "resume": "Interdiction des terrasses chauffées et des braseros électriques ou à gaz.",
    "explication": "Les terrasses chauffées (lampadaires infrarouges, braseros à gaz) sont interdites. L'énergie utilisée est un gaspillage inutile. Des alternatives existent (couvertures, parois vitrées).",
    "chiffre_cle": "Les terrasses chauffées consomment autant qu'une ville de 100 000 habitants",
    "exemple_concret": "Un café installe des plaids et des parois pour l'hiver, sans chauffage extérieur.",
    "financement": "Sans coût - réglementation",
    "motscles": ["terrasse chauffée", "braseiro", "énergie", "gaspillage", "café"],
    "statut": "mesure"
  },
  {
    "id": 87,
    "titre": "Plan de réensauvagement des forêts",
    "categorie": "ecologie",
    "sous_categorie": "foret",
    "public": ["tous"],
    "resume": "Laisse 25% des forêts françaises en libre évolution (sans intervention humaine).",
    "explication": "Un quart de la surface forestière française est laissé en libre évolution (pas de coupe, pas de plantation, pas de chasse). Objectif : restaurer la biodiversité forestière.",
    "chiffre_cle": "Actuellement, moins de 1% des forêts françaises sont en libre évolution",
    "exemple_concret": "Une parcelle de forêt de Fontainebleau n'est plus entretenue, la nature reprend ses droits.",
    "financement": "Sans coût - réorientation de la gestion",
    "motscles": ["forêt", "libre évolution", "biodiversité", "réensauvagement", "nature"],
    "statut": "mesure"
  },
  {
    "id": 88,
    "titre": "Création d'un revenu carbone citoyen",
    "categorie": "ecologie",
    "sous_categorie": "climat",
    "public": ["tous"],
    "resume": "Distribution d'un revenu carbone aux ménages les plus modestes pour financer leur transition.",
    "explication": "Un revenu carbone citoyen est distribué aux 20% des ménages les plus modestes (environ 100€ par mois). Il permet de financer la rénovation du logement, l'achat d'un vélo ou d'une voiture électrique, l'isolation.",
    "chiffre_cle": "Les 10% les plus riches polluent 5 fois plus que les 50% les plus pauvres",
    "exemple_concret": "Une famille modeste reçoit 1200€ par an pour changer sa chaudière au fioul.",
    "financement": "4 milliards d'euros par an, financé par l'ISF climatique",
    "motscles": ["revenu carbone", "transition", "pauvreté", "énergie", "justice climatique"],
    "statut": "mesure"
  },
  {
    "id": 89,
    "titre": "Interdiction des marmites norvégiennes (surpêche)",
    "categorie": "ecologie",
    "sous_categorie": "mer",
    "public": ["pecheurs"],
    "resume": "Interdiction des marmites norvégiennes (filets immenses) qui capturent tous les poissons.",
    "explication": "Les marmites norvégiennes (filets dérivants de plusieurs kilomètres) sont interdites. Elles capturent tous les poissons sans sélectivité et détruisent les fonds marins.",
    "chiffre_cle": "90% des stocks de poissons sont surpêchés en Méditerranée",
    "exemple_concret": "Un pêcheur doit utiliser un filet sélectif qui laisse passer les juvéniles.",
    "financement": "Aides à la reconversion des pêcheurs vers des méthodes durables",
    "motscles": ["marmite norvégienne", "surpêche", "filet", "pêche", "Méditerranée"],
    "statut": "mesure"
  },
  {
    "id": 90,
    "titre": "Plan de lutte contre les espèces invasives",
    "categorie": "ecologie",
    "sous_categorie": "biodiversite",
    "public": ["tous"],
    "resume": "Plan national d'éradication des espèces exotiques envahissantes (ragondin, frelon asiatique, jussie).",
    "explication": "Un plan national de lutte contre les espèces invasives est lancé : éradication ciblée, prévention des introductions, sensibilisation. Priorité au ragondin, frelon asiatique, écrevisse de Louisiane, jussie, ambroisie.",
    "chiffre_cle": "Les espèces invasives coûtent 1,2 milliard d'euros par an en France",
    "exemple_concret": "Un piégeage systématique du ragondin est organisé dans les zones humides.",
    "financement": "200 millions d'euros par an",
    "motscles": ["espèce invasive", "ragondin", "frelon asiatique", "ambroisie", "biodiversité"],
    "statut": "mesure"
  },
  {
    "id": 91,
    "titre": "Interdiction des pesticides de synthèse dans les jardins",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["particuliers"],
    "resume": "Interdiction totale des pesticides de synthèse pour les particuliers (jardins, balcons).",
    "explication": "Les pesticides de synthèse (Roundup, insecticides) sont interdits à la vente pour les particuliers. Seuls les produits bio (purin d'ortie, savon noir, etc.) sont autorisés.",
    "chiffre_cle": "Les jardiniers amateurs utilisent 20% des pesticides vendus",
    "exemple_concret": "Un jardinier utilise du purin d'ortie contre les pucerons.",
    "financement": "Sans coût - réglementation",
    "motscles": ["pesticides", "jardin", "particulier", "Roundup", "bio"],
    "statut": "mesure"
  },
  {
    "id": 92,
    "titre": "Plan de protection des zones humides méditerranéennes",
    "categorie": "ecologie",
    "sous_categorie": "eau",
    "public": ["tous"],
    "resume": "Protection renforcée de la Camargue, de la Crau et des étangs languedociens.",
    "explication": "Les zones humides méditerranéennes (Camargue, Crau, étangs du Languedoc) sont protégées : interdiction des pompages agricoles excessifs, limitation de l'urbanisation, restauration des écosystèmes.",
    "chiffre_cle": "La Camargue a perdu 50% de ses zones humides en 50 ans",
    "exemple_concret": "Les rizières de Camargue reviennent à des pratiques sans pesticide.",
    "financement": "200 millions d'euros sur 10 ans",
    "motscles": ["Camargue", "Crau", "Languedoc", "zone humide", "flamant rose"],
    "statut": "mesure"
  },
  {
    "id": 93,
    "titre": "Interdiction des forages pétroliers en mer",
    "categorie": "ecologie",
    "sous_categorie": "mer",
    "public": ["entreprises"],
    "resume": "Interdiction de tout nouveau forage pétrolier offshore, arrêt progressif des forages existants.",
    "explication": "Les nouveaux forages pétroliers en mer sont interdits. Les forages existants (notamment en Guyane et en Méditerranée) sont arrêtés progressivement d'ici 2030.",
    "chiffre_cle": "La France a 130 permis de recherche d'hydrocarbures offshore",
    "exemple_concret": "Le permis de recherche au large de la Guyane est annulé.",
    "financement": "Sans coût - réglementation",
    "motscles": ["forage", "pétrole", "offshore", "mer", "Guyane"],
    "statut": "mesure"
  },
  {
    "id": 94,
    "titre": "Plan de restauration des tourbières",
    "categorie": "ecologie",
    "sous_categorie": "biodiversite",
    "public": ["tous"],
    "resume": "Restauration des 100 000 hectares de tourbières dégradées en France.",
    "explication": "Les tourbières (marais tourbeux) sont des puits de carbone exceptionnels. Un plan de restauration est lancé pour renaturer 100 000 ha de tourbières asséchées (drainage agricole, extraction de tourbe).",
    "chiffre_cle": "Les tourbières stockent 10 fois plus de carbone que les forêts",
    "exemple_concret": "La tourbière du Jura, asséchée pour l'agriculture, est renaturée.",
    "financement": "300 millions d'euros",
    "motscles": ["tourbière", "marais", "carbone", "restauration", "biodiversité"],
    "statut": "mesure"
  },
  {
    "id": 95,
    "titre": "Création d'une filière textile écoresponsable française",
    "categorie": "ecologie",
    "sous_categorie": "industrie",
    "public": ["tous"],
    "resume": "Relocalisation d'une filière textile écoresponsable (lin, chanvre, laine) en France.",
    "explication": "Une filière textile écoresponsable est recréée en France : culture du lin et du chanvre, élevage de moutons pour la laine, ateliers de tissage et de confection. Objectif : 50% des vêtements achetés en France fabriqués en France d'ici 2030.",
    "chiffre_cle": "98% des vêtements achetés en France sont importés",
    "exemple_concret": "Un T-shirt en lin cultivé en Normandie, filé dans le Nord, cousu dans le Vieux-Lyon.",
    "financement": "500 millions d'euros pour les filières",
    "motscles": ["textile", "lin", "chanvre", "laine", "relocalisation"],
    "statut": "mesure"
  },
  {
    "id": 96,
    "titre": "Interdiction des colles pour le bâti scolaire contenant des perturbateurs endocriniens",
    "categorie": "ecologie",
    "sous_categorie": "batiment",
    "public": ["tous"],
    "resume": "Interdiction des colles et matériaux de construction contenant des perturbateurs endocriniens.",
    "explication": "Les colles, peintures, revêtements de sol et isolants contenant des perturbateurs endocriniens (phtalates, bisphénol A, etc.) sont interdits, notamment dans le bâti scolaire et hospitalier.",
    "chiffre_cle": "Les enfants passent 80% de leur temps dans des espaces intérieurs",
    "exemple_concret": "Une école utilise des peintures sans COV (composés organiques volatils).",
    "financement": "Sans coût - réglementation",
    "motscles": ["perturbateur endocrinien", "colles", "peinture", "école", "matériaux"],
    "statut": "mesure"
  },
  {
    "id": 97,
    "titre": "Plan de lutte contre les algues vertes en Bretagne",
    "categorie": "ecologie",
    "sous_categorie": "pollution",
    "public": ["bretons"],
    "resume": "Plan d'éradication des algues vertes en Bretagne : réduction des nitrates, ramassage mécanique.",
    "explication": "Un plan d'éradication des algues vertes est lancé : réduction de 50% des nitrates agricoles, ramassage mécanique systématique, création de lagunes pour capter les nitrates.",
    "chiffre_cle": "Les algues vertes émettent du gaz mortel (hydrogène sulfuré)",
    "exemple_concret": "Un éleveur breton plante des haies pour capter les nitrates.",
    "financement": "500 millions d'euros sur 5 ans",
    "motscles": ["algues vertes", "Bretagne", "nitrates", "élevage", "littoral"],
    "statut": "mesure"
  },
  {
    "id": 98,
    "titre": "Interdiction des bilans carbone 'compensés' (greenwashing)",
    "categorie": "ecologie",
    "sous_categorie": "consommation",
    "public": ["entreprises"],
    "resume": "Interdiction des mentions 'neutre en carbone' ou 'compensé' sans preuve vérifiée.",
    "explication": "Les entreprises ne peuvent plus utiliser les mentions 'neutre en carbone', 'zéro émission' ou 'compensé' sans une certification indépendante et une traçabilité complète des compensations.",
    "chiffre_cle": "80% des compensations carbone sont inefficaces (selon la Commission européenne)",
    "exemple_concret": "Une compagnie aérienne ne peut plus prétendre compenser ses vols.",
    "financement": "Sans coût - réglementation",
    "motscles": ["greenwashing", "compensation", "carbone", "neutre", "publicité"],
    "statut": "mesure"
  },
  {
    "id": 99,
    "titre": "Plan de plantation de 100 millions d'arbres en ville",
    "categorie": "ecologie",
    "sous_categorie": "urbanisme",
    "public": ["tous"],
    "resume": "Plantation de 100 millions d'arbres en ville d'ici 2030 pour lutter contre les îlots de chaleur.",
    "explication": "Un plan de plantation massive d'arbres en ville est lancé : 100 millions d'arbres plantés, priorité aux zones défavorisées et aux abords des écoles, hôpitaux et maisons de retraite.",
    "chiffre_cle": "Un arbre mature abat 50°C sur son feuillage en été",
    "exemple_concret": "Une rue de Marseille est entièrement plantée de platanes.",
    "financement": "2 milliards d'euros pour les communes",
    "motscles": ["arbre", "ville", "îlot de chaleur", "plantation", "végétalisation"],
    "statut": "mesure"
  },
  {
    "id": 100,
    "titre": "Interdiction des produits phytosanitaires dans les parcs et jardins publics",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Interdiction de tous les produits phytosanitaires dans les parcs, jardins et cimetières publics.",
    "explication": "Les pesticides, fongicides et herbicides sont interdits dans tous les espaces verts publics (parcs, jardins, cimetières, stades, golfs municipaux). Seule la gestion différenciée (zéro phyto) est autorisée.",
    "chiffre_cle": "Déjà appliqué dans 70% des communes",
    "exemple_concret": "Un cimetière municipal est entretenu avec des moutons tontenuse.",
    "financement": "Sans coût - réglementation",
    "motscles": ["phyto", "pesticides", "parc", "jardin", "zéro phyto"],
    "statut": "mesure"
  }
];

// Export pour utilisation
if (typeof module !== 'undefined' && module.exports) {
  module.exports = mesures;
}
