// data.js - Base de données complète du programme L'Avenir en commun
// Version 1.0 - 50 mesures prioritaires

const mesures = [
  // === TRAVAIL & RETRAITE (10) ===
  {
    "id": 1,
    "titre": "Retraite à 60 ans",
    "categorie": "travail",
    "sous_categorie": "retraite",
    "public": ["seniors", "actifs"],
    "resume": "Retour à la retraite à 60 ans avec 40 annuités de cotisation.",
    "explication": "La réforme Macron qui repoussait l'âge à 64 ans est abrogée. On revient au système antérieur : départ possible à 60 ans pour une carrière complète de 40 ans. Les métiers pénibles conservent des départs anticipés.",
    "chiffre_cle": "83% des Français soutiennent une pension minimale au niveau du SMIC",
    "exemple_concret": "Mme Martin, aide-soignante, a commencé à 20 ans. Elle pourra partir à 60 ans avec 1450€ net (contre 64 ans et 980€ aujourd'hui).",
    "financement": "Augmentation de 0,25 point par an des cotisations vieillesse + soumission des dividendes à cotisation",
    "url": "/2100/mesures/retraite-60-ans.html",
    "motscles": ["retraite", "60 ans", "pension", "senior", "carrière longue", "départ anticipé"],
    "statut": "mesure_cle"
  },
  {
    "id": 2,
    "titre": "SMIC à 1600€ net",
    "categorie": "travail",
    "sous_categorie": "salaire",
    "public": ["actifs", "jeunes"],
    "resume": "Augmentation immédiate du SMIC à 1600 euros net par mois.",
    "explication": "Le SMIC est porté à 1600€ net dès l'arrivée au pouvoir. Cette augmentation bénéficie directement à 2,3 millions de salariés et tire tous les salaires inférieurs à 2000€ vers le haut (effet d'entraînement).",
    "chiffre_cle": "56% des salariés français gagnent moins de 2000€ net par mois",
    "exemple_concret": "Un caissier au SMIC passe de 1210€ à 1600€ net par mois, soit +390€.",
    "financement": "Hausse du SMIC = 1,8Md€ par an pour l'État (compensé par les recettes fiscales supplémentaires et la croissance)",
    "url": "/2100/mesures/smic-1600.html",
    "motscles": ["SMIC", "salaire", "pouvoir d'achat", "1600 euros", "bas salaires"],
    "statut": "mesure_cle"
  },
  {
    "id": 3,
    "titre": "Semaine de 4 jours (32 heures)",
    "categorie": "travail",
    "sous_categorie": "temps_de_travail",
    "public": ["actifs"],
    "resume": "Passage aux 32 heures pour les métiers pénibles, généralisation négociée.",
    "explication": "Les 32 heures deviennent la norme pour les métiers pénibles et le travail de nuit. Une conférence nationale sur le partage du temps de travail décidera des modalités et du calendrier de la transition vers les 32 heures pour tous.",
    "chiffre_cle": "70% des Français sont favorables à la semaine de 4 jours (Ifop, 2024)",
    "exemple_concret": "Un ouvrier du bâtiment travaillant de nuit passe de 35h à 32h sans perte de salaire.",
    "financement": "Financement par les gains de productivité et la réduction du chômage",
    "url": "/2100/mesures/semaine-4-jours.html",
    "motscles": ["32 heures", "semaine de 4 jours", "temps de travail", "pénibilité", "travail de nuit"],
    "statut": "mesure_cle"
  },
  {
    "id": 4,
    "titre": "Fin des CDD précaires",
    "categorie": "travail",
    "sous_categorie": "emploi",
    "public": ["actifs", "jeunes"],
    "resume": "Quota maximal de contrats précaires : 10% dans les PME, 5% dans les grandes entreprises.",
    "explication": "Pour lutter contre la précarisation massive, un quota limite le recours aux CDD, intérim et contrats courts. Les entreprises doivent embaucher en CDI pour leurs missions pérennes.",
    "chiffre_cle": "87% des embauches se font en contrats courts",
    "exemple_concret": "Une grande surface qui emploie 200 personnes ne pourra avoir que 10 CDD (5%) au lieu de 80 aujourd'hui.",
    "financement": "Sans coût pour l'État - simple réallocation des contrats",
    "url": "/2100/mesures/fin-cdd-precaires.html",
    "motscles": ["CDD", "précarité", "intérim", "CDI", "contrat court"],
    "statut": "mesure_cle"
  },
  {
    "id": 5,
    "titre": "Garantie d'emploi pour les chômeurs de longue durée",
    "categorie": "travail",
    "sous_categorie": "emploi",
    "public": ["chomeurs"],
    "resume": "Tout chômeur de longue durée peut se voir proposer un emploi utile, payé au SMIC.",
    "explication": "L'État garantit un emploi dans un secteur utile (écologie, social, services publics) à tout chômeur volontaire après 12 mois d'inscription. Emploi à temps choisi (20-35h/semaine).",
    "chiffre_cle": "87% des Français soutiennent cette mesure",
    "exemple_concret": "Un informaticien au chômage depuis 14 mois peut être embauché pour former des seniors au numérique dans une association.",
    "financement": "18 milliards d'euros par an pour 1,8 million d'emplois",
    "url": "/2100/mesures/garantie-emploi.html",
    "motscles": ["chômage", "chômeur", "garantie d'emploi", "insertion", "longue durée"],
    "statut": "mesure_cle"
  },
  {
    "id": 6,
    "titre": "Rétablissement d'une assurance chômage protectrice",
    "categorie": "travail",
    "sous_categorie": "chomage",
    "public": ["chomeurs", "actifs"],
    "resume": "Indemnisation dès le premier jour, calculée sur les derniers salaires, fin des radiations abusives.",
    "explication": "Abrogation des réformes Macron de l'assurance chômage. Retour à une indemnisation protectrice : pas de délai de carence, calcul sur les 12 derniers mois travaillés, fin de la dégressibilité pour les cadres.",
    "chiffre_cle": "14 000 personnes meurent chaque année des conséquences du chômage",
    "exemple_concret": "Un cadre perd son emploi : son allocation ne diminue plus après 6 mois.",
    "financement": "Redistribution des 6 milliards d'euros prélevés sur l'Unédic par l'État",
    "url": "/2100/mesures/assurance-chomage-protectrice.html",
    "motscles": ["chômage", "assurance chômage", "indemnisation", "Pôle emploi", "radiation"],
    "statut": "mesure_cle"
  },
  {
    "id": 7,
    "titre": "Sécurité sociale professionnelle",
    "categorie": "travail",
    "sous_categorie": "formation",
    "public": ["actifs", "chomeurs"],
    "resume": "Les droits sociaux (formation, congés, ancienneté) sont attachés à la personne, pas au contrat.",
    "explication": "Comme la carte Vitale garantit la continuité des droits santé, la sécurité sociale professionnelle garantit les droits à la formation, aux congés et à l'ancienneté tout au long de la vie, y compris entre deux contrats.",
    "chiffre_cle": "Droit à 36 heures de formation par an par salarié",
    "exemple_concret": "Un intérimaire cumule ses droits à formation même entre deux missions.",
    "financement": "Financement par les cotisations sociales des entreprises",
    "url": "/2100/mesures/securite-sociale-professionnelle.html",
    "motscles": ["formation", "droits sociaux", "carrière", "intérim", "précarité"],
    "statut": "mesure"
  },
  {
    "id": 8,
    "titre": "Fin du travail détaché",
    "categorie": "travail",
    "sous_categorie": "emploi",
    "public": ["actifs"],
    "resume": "Un travailleur sur le sol français paie les cotisations françaises et a les mêmes droits.",
    "explication": "Le système du travail détaché, qui permet à des entreprises de faire travailler des étrangers avec les cotisations du pays d'origine, est aboli. Tous les travailleurs sur le territoire français bénéficient des mêmes droits et cotisations.",
    "chiffre_cle": "68% des Français sont favorables à l'interdiction du travail détaché",
    "exemple_concret": "Un ouvrier polonais sur un chantier en France cotise à la Sécu française et touche les mêmes indemnités qu'un ouvrier français.",
    "financement": "Sans coût - rééquilibrage des cotisations",
    "url": "/2100/mesures/fin-travail-detache.html",
    "motscles": ["travail détaché", "dumping social", "cotisations", "travailleurs étrangers"],
    "statut": "mesure"
  },
  {
    "id": 9,
    "titre": "Reconnaissance du burn-out en maladie professionnelle",
    "categorie": "travail",
    "sous_categorie": "sante_travail",
    "public": ["actifs"],
    "resume": "Le burn-out est reconnu comme maladie professionnelle, avec prise en charge et indemnisation.",
    "explication": "L'épuisement professionnel (burn-out) entre dans le tableau des maladies professionnelles. Les victimes bénéficient d'une prise en charge par la Sécu, d'une indemnisation et d'un parcours de soins adapté.",
    "chiffre_cle": "81% des Français soutiennent cette mesure",
    "exemple_concret": "Un salarié en burn-out est reconnu en arrêt maladie professionnelle avec indemnisation à 100% du salaire.",
    "financement": "Prise en charge par la branche AT/MP de la Sécu",
    "url": "/2100/mesures/burnout-maladie-professionnelle.html",
    "motscles": ["burn-out", "épuisement", "santé mentale", "maladie professionnelle", "stress"],
    "statut": "mesure"
  },
  {
    "id": 10,
    "titre": "35 heures effectives",
    "categorie": "travail",
    "sous_categorie": "temps_de_travail",
    "public": ["actifs"],
    "resume": "Rétablissement des 35 heures comme norme, fin des heures supplémentaires défiscalisées.",
    "explication": "Les heures supplémentaires sont majorées à 25% pour les 4 premières et 50% au-delà. Fin du contournement des 35 heures par l'annualisation et les forfaits-jours abusifs.",
    "chiffre_cle": "Les Français travaillent en moyenne 37h par semaine",
    "exemple_concret": "Un employé en forfait-jours abusif retrouve un décompte horaire et des majorations pour heures sup.",
    "financement": "Sans coût - création d'emplois par partage du travail",
    "url": "/2100/mesures/35-heures-effectives.html",
    "motscles": ["35 heures", "heures supplémentaires", "forfait jours", "annualisation"],
    "statut": "mesure"
  },

  // === ÉCOLOGIE & CLIMAT (12) ===
  {
    "id": 11,
    "titre": "100% énergies renouvelables en 2050",
    "categorie": "ecologie",
    "sous_categorie": "energie",
    "public": ["tous"],
    "resume": "Objectif 100% d'énergies renouvelables en 2050, sortie du nucléaire et des énergies fossiles.",
    "explication": "La France s'engage à atteindre 100% d'énergies renouvelables (solaire, éolien, hydrolien, géothermie) d'ici 2050. Sortie progressive du nucléaire et arrêt des subventions aux énergies fossiles.",
    "chiffre_cle": "74% des Français sont favorables à un objectif 100% renouvelable",
    "exemple_concret": "La Réunion, territoire pilote, atteint 100% d'énergies renouvelables grâce au solaire, l'hydrolien et la géothermie.",
    "financement": "93 milliards d'euros d'investissement sur le quinquennat",
    "url": "/2100/mesures/100-renouvelables.html",
    "motscles": ["énergies renouvelables", "solaire", "éolien", "sortie nucléaire", "transition énergétique"],
    "statut": "mesure_cle"
  },
  {
    "id": 12,
    "titre": "Rénovation thermique des logements",
    "categorie": "ecologie",
    "sous_categorie": "logement",
    "public": ["tous", "seniors", "precaires"],
    "resume": "700 000 logements rénovés par an, interdiction de location des passoires thermiques.",
    "explication": "Plan massif de rénovation énergétique : 700 000 logements par an sont isolés thermiquement. Les passoires thermiques (classes F et G) ne pourront plus être louées à partir de 2025. Aides à 100% pour les ménages modestes.",
    "chiffre_cle": "4,8 millions de passoires thermiques en France",
    "exemple_concret": "Un propriétaire d'un appartement classé G reçoit des aides pour l'isolation avant de pouvoir le relouer.",
    "financement": "Inclus dans le plan d'investissement écologique",
    "url": "/2100/mesures/renovation-thermique.html",
    "motscles": ["rénovation", "isolation", "passoire thermique", "énergie", "logement", "DPE"],
    "statut": "mesure_cle"
  },
  {
    "id": 13,
    "titre": "Interdiction du glyphosate",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Interdiction immédiate du glyphosate et des néonicotinoïdes, y compris dans les produits importés.",
    "explication": "Le glyphosate et les néonicotinoïdes sont interdits en France dès l'arrivée au pouvoir. L'interdiction s'applique aussi aux produits importés pour éviter le dumping. Un plan d'accompagnement aide les agriculteurs à se convertir.",
    "chiffre_cle": "89% des Français sont favorables à l'interdiction du glyphosate",
    "exemple_concret": "Un agriculteur utilisant du glyphosate reçoit une aide pour passer au désherbage mécanique.",
    "financement": "Caisse de défaisance pour les agriculteurs convertis au bio",
    "url": "/2100/mesures/interdiction-glyphosate.html",
    "motscles": ["glyphosate", "pesticides", "néonicotinoïdes", "agriculture", "bio"],
    "statut": "mesure_cle"
  },
  {
    "id": 14,
    "titre": "Sortie des fermes-usines",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Interdiction des élevages intensifs et sortie progressive des fermes-usines d'ici 2027.",
    "explication": "Les fermes-usines (élevages de plus de 150 truies ou vaches laitières, élevages en cage, etc.) sont interdites. Un accompagnement financier aide les éleveurs à se reconvertir vers des élevages extensifs ou des cultures végétales.",
    "chiffre_cle": "80% des animaux d'élevage sont en élevage intensif",
    "exemple_concret": "Un éleveur de porcs en batterie reçoit une aide pour passer à un élevage plein air.",
    "financement": "Aide à la transition budgétée dans le plan agricole",
    "url": "/2100/mesures/sortie-fermes-usines.html",
    "motscles": ["ferme-usine", "élevage intensif", "bien-être animal", "agro-industrie"],
    "statut": "mesure_cle"
  },
  {
    "id": 15,
    "titre": "Règle verte dans la Constitution",
    "categorie": "ecologie",
    "sous_categorie": "institutions",
    "public": ["tous"],
    "resume": "Inscription dans la Constitution du principe : ne pas prendre à la nature plus qu'elle ne peut reconstituer.",
    "explication": "La 'règle verte' devient un principe constitutionnel. Toute loi, tout projet d'infrastructure doit respecter cette limite. Le droit de propriété ne peut prévaloir sur la protection de l'eau, l'air, la biodiversité.",
    "chiffre_cle": "83% des Français soutiennent ce principe",
    "exemple_concret": "Un projet d'autoroute pourrait être annulé s'il détruit une zone humide indispensable au cycle de l'eau.",
    "financement": "Sans coût direct - changement de paradigme juridique",
    "url": "/2100/mesures/regle-verte-constitution.html",
    "motscles": ["règle verte", "Constitution", "limites planétaires", "biodiversité", "écologie"],
    "statut": "mesure_cle"
  },
  {
    "id": 16,
    "titre": "Zéro artificialisation nette des sols",
    "categorie": "ecologie",
    "sous_categorie": "amenagement",
    "public": ["tous"],
    "resume": "Interdiction du bétonnage des terres agricoles et naturelles dès 2025.",
    "explication": "Plus aucune construction ne peut artificialiser des terres agricoles ou naturelles. Les constructions nouvelles doivent se faire sur des friches ou des terrains déjà artificialisés.",
    "chiffre_cle": "20 000 à 30 000 hectares artificialisés chaque année en France",
    "exemple_concret": "Un entrepôt Amazon ne peut plus s'installer sur une terre agricole. Il doit reconvertir une friche industrielle.",
    "financement": "Sans coût - réorientation de l'aménagement",
    "url": "/2100/mesures/zero-artificialisation.html",
    "motscles": ["artificialisation", "bétonnage", "sols", "agriculture", "urbanisme"],
    "statut": "mesure"
  },
  {
    "id": 17,
    "titre": "Fin des vols intérieurs",
    "categorie": "ecologie",
    "sous_categorie": "transports",
    "public": ["tous"],
    "resume": "Suppression des lignes aériennes intérieures quand une alternative en train existe en moins de 4h.",
    "explication": "Les vols intérieurs sont supprimés lorsqu'un trajet en train de moins de 4 heures est possible. Cette mesure, demandée par la Convention citoyenne pour le climat, réduit massivement les émissions du transport aérien.",
    "chiffre_cle": "Le secteur des transports pèse 31% des émissions de gaz à effet de serre",
    "exemple_concret": "Paris-Lyon en avion est supprimé : les voyageurs prennent le TGV (2h).",
    "financement": "Sans coût - report modal vers le train",
    "url": "/2100/mesures/fin-vols-interieurs.html",
    "motscles": ["vol intérieur", "avion", "train", "TGV", "Convention citoyenne pour le climat"],
    "statut": "mesure"
  },
  {
    "id": 18,
    "titre": "Développement du fret ferroviaire",
    "categorie": "ecologie",
    "sous_categorie": "transports",
    "public": ["tous"],
    "resume": "Plan massif pour passer de 9% à 18% de fret ferroviaire, réouverture des gares de triage.",
    "explication": "Investissement massif dans le fret ferroviaire pour sortir des camions. Réouverture des gares de triage, retour du wagon isolé, développement du ferroutage.",
    "chiffre_cle": "9% du fret est ferroviaire en France contre 18% en moyenne européenne",
    "exemple_concret": "Les camions traversant la France entre l'Espagne et le Nord sont reportés sur le train.",
    "financement": "44 milliards d'euros sur le quinquennat",
    "url": "/2100/mesures/fret-ferroviaire.html",
    "motscles": ["fret", "train", "camion", "logistique", "ferroutage"],
    "statut": "mesure"
  },
  {
    "id": 19,
    "titre": "Plan eau : gratuité des premiers m³",
    "categorie": "ecologie",
    "sous_categorie": "eau",
    "public": ["tous", "precaires"],
    "resume": "Gratuité des premiers mètres cubes d'eau indispensables à la vie, tarification progressive.",
    "explication": "L'eau est un bien commun : les premiers m³ nécessaires à une vie digne (boisson, hygiène, cuisine) sont gratuits. Au-delà, une tarification progressive pénalise les usages abusifs (piscines, arrosage intensif).",
    "chiffre_cle": "80% des Français soutiennent la gratuité des premiers m³",
    "exemple_concret": "Une famille de 4 personnes ne paie plus pour ses 120 premiers m³ par an (usage domestique normal).",
    "financement": "Financé par la tarification progressive et le retour en régie publique",
    "url": "/2100/mesures/plan-eau.html",
    "motscles": ["eau", "gratuité", "tarification progressive", "bien commun", "régie publique"],
    "statut": "mesure"
  },
  {
    "id": 20,
    "titre": "Interdiction des plastiques à usage unique",
    "categorie": "ecologie",
    "sous_categorie": "dechets",
    "public": ["tous"],
    "resume": "Interdiction immédiate de tous les plastiques à usage unique, généralisation de la consigne.",
    "explication": "Les plastiques à usage unique (gobelets, couverts, pailles, emballages jetables) sont interdits. La consigne pour les bouteilles et bocaux en verre est généralisée.",
    "chiffre_cle": "360 millions de tonnes de plastique produites chaque année dans le monde",
    "exemple_concret": "Au supermarché, plus de suremballage : les légumes sont en vrac, les bouteilles sont consignées.",
    "financement": "Soutien aux filières de réemploi",
    "url": "/2100/mesures/fin-plastiques-usage-unique.html",
    "motscles": ["plastique", "usage unique", "consigne", "déchets", "suremballage"],
    "statut": "mesure"
  },
  {
    "id": 21,
    "titre": "Moratoire sur les OGM",
    "categorie": "ecologie",
    "sous_categorie": "agriculture",
    "public": ["tous"],
    "resume": "Moratoire sur tous les OGM, y compris les 'OGM cachés' issus des nouvelles techniques génomiques.",
    "explication": "Tous les OGM sont interdits, y compris ceux issus des nouvelles techniques génomiques (NBT). La recherche publique sur les alternatives est renforcée.",
    "chiffre_cle": "La France est le premier consommateur européen de produits sans OGM",
    "exemple_concret": "Un agriculteur ne peut plus planter de maïs OGM, même les variétés issues de mutagénèse.",
    "financement": "Sans coût - réorientation de la recherche",
    "url": "/2100/mesures/moratoire-ogm.html",
    "motscles": ["OGM", "NBT", "mutagénèse", "semences", "agriculture"],
    "statut": "mesure"
  },
  {
    "id": 22,
    "titre": "ISF climatique",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["riches"],
    "resume": "Rétablissement de l'ISF avec un volet climatique taxant les actifs polluants.",
    "explication": "L'ISF supprimé par Macron est rétabli. Un volet climatique ajoute une taxation sur les actifs liés aux énergies fossiles, aux mines, à la déforestation.",
    "chiffre_cle": "Les 10% les plus riches polluent 5 fois plus que la moitié la plus pauvre",
    "exemple_concret": "Un portefeuille d'actions contenant du pétrole est plus taxé qu'un portefeuille vert.",
    "financement": "10 milliards d'euros par an",
    "url": "/2100/mesures/isf-climatique.html",
    "motscles": ["ISF", "impôt", "riches", "climat", "actifs polluants"],
    "statut": "mesure_cle"
  },

  // === SANTÉ (6) ===
  {
    "id": 23,
    "titre": "100% Sécu",
    "categorie": "sante",
    "sous_categorie": "remboursement",
    "public": ["tous", "precaires", "seniors"],
    "resume": "Remboursement intégral de tous les soins prescrits par la Sécurité sociale.",
    "explication": "Fin des tickets modérateurs et des restes à charge. Tous les soins prescrits (médecine, dentaire, optique, audioprothèse) sont remboursés à 100% par la Sécu. Les mutuelles sont intégrées au système public.",
    "chiffre_cle": "59% des Français ont renoncé à des soins pour raisons financières",
    "exemple_concret": "Une paire de lunettes à 300€ : fin du reste à charge de 150€, tout est remboursé.",
    "financement": "14,35 milliards d'euros par an, financé par la fin des frais de gestion des mutuelles et la régulation des prix",
    "url": "/2100/mesures/100-secu.html",
    "motscles": ["Sécu", "remboursement", "mutuelle", "soins", "déserts médicaux"],
    "statut": "mesure_cle"
  },
  {
    "id": 24,
    "titre": "Fin des déserts médicaux",
    "categorie": "sante",
    "sous_categorie": "acces_soins",
    "public": ["tous", "ruraux", "precaires"],
    "resume": "Maillage du territoire en centres de santé publics, fin des déserts médicaux en 5 ans.",
    "explication": "Création de centres de santé pluridisciplinaires publics partout en France. Recrutement de médecins publics. Augmentation du numerus clausus. Obligation de permanence des soins.",
    "chiffre_cle": "1 Français sur 5 vit dans un désert médical",
    "exemple_concret": "Dans un village sans médecin, un centre de santé public ouvre avec 3 généralistes et 2 infirmiers.",
    "financement": "Inclus dans le plan de recrutement des soignants (100 000 postes)",
    "url": "/2100/mesures/fin-deserts-medicaux.html",
    "motscles": ["désert médical", "médecin", "centre de santé", "accès aux soins", "numerus clausus"],
    "statut": "mesure_cle"
  },
  {
    "id": 25,
    "titre": "Légalisation du cannabis",
    "categorie": "sante",
    "sous_categorie": "addictions",
    "public": ["tous"],
    "resume": "Légalisation encadrée du cannabis (production, vente, consommation) sous monopole d'État.",
    "explication": "Le cannabis est légalisé sous contrôle de l'État. La production, la vente et la consommation sont régulées. Les recettes fiscales financent la prévention et la lutte contre les addictions.",
    "chiffre_cle": "57% des Français soutiennent la légalisation",
    "exemple_concret": "Un consommateur peut acheter du cannabis dans un bureau de tabac agréé, avec un prix fixé par l'État.",
    "financement": "Les taxes rapportent 5 milliards d'euros par an",
    "url": "/2100/mesures/legalisation-cannabis.html",
    "motscles": ["cannabis", "légalisation", "drogue", "prévention", "addiction"],
    "statut": "mesure"
  },
  {
    "id": 26,
    "titre": "Pôle public du médicament",
    "categorie": "sante",
    "sous_categorie": "medicaments",
    "public": ["tous"],
    "resume": "Création d'un pôle public pour produire les médicaments essentiels en France.",
    "explication": "Un pôle public du médicament est créé pour relocaliser la production des médicaments essentiels (antibiotiques, vaccins, paracétamol). Fin des pénuries et des prix abusifs.",
    "chiffre_cle": "80% des médicaments remboursés sont importés",
    "exemple_concret": "Lors d'une pénurie de doliprane, le pôle public relance la production en France.",
    "financement": "Nationalisation des filiales critiques, financement public",
    "url": "/2100/mesures/pole-public-medicament.html",
    "motscles": ["médicament", "pénurie", "relocalisation", "doliprane", "vaccin"],
    "statut": "mesure"
  },
  {
    "id": 27,
    "titre": "Droit de mourir dans la dignité",
    "categorie": "sante",
    "sous_categorie": "fin_de_vie",
    "public": ["seniors", "tous"],
    "resume": "Constitutionnalisation du droit de mourir dans la dignité et aide à mourir légalisée.",
    "explication": "Le droit à mourir dans la dignité est inscrit dans la Constitution. L'aide médicale à mourir (euthanasie et suicide assisté) est légalisée, encadrée et accessible.",
    "chiffre_cle": "89% des Français soutiennent l'euthanasie, 92% le suicide assisté",
    "exemple_concret": "Un patient en phase terminale peut demander une aide médicale à mourir, après avis collégial.",
    "financement": "Sans coût supplémentaire",
    "url": "/2100/mesures/droit-mourir-dignite.html",
    "motscles": ["fin de vie", "euthanasie", "suicide assisté", "dignité", "soins palliatifs"],
    "statut": "mesure"
  },
  {
    "id": 28,
    "titre": "Plan santé mentale",
    "categorie": "sante",
    "sous_categorie": "sante_mentale",
    "public": ["tous", "jeunes"],
    "resume": "Réouverture des lits de psychiatrie, recrutement de psychologues, renforcement des CMP.",
    "explication": "Plan d'urgence pour la santé mentale : réouverture des lits fermés, recrutement massif de psychologues et de psychiatres, renforcement des centres médico-psychologiques (CMP) partout sur le territoire.",
    "chiffre_cle": "20% de la population souffre de troubles psychiques dans sa vie",
    "exemple_concret": "Un adolescent en dépression peut consulter un psychologue gratuitement dans son CMP de secteur.",
    "financement": "Inclus dans le plan de recrutement des soignants",
    "url": "/2100/mesures/plan-sante-mentale.html",
    "motscles": ["santé mentale", "psychiatrie", "psychologue", "CMP", "dépression"],
    "statut": "mesure"
  },

  // === ÉDUCATION (5) ===
  {
    "id": 29,
    "titre": "Fin de Parcoursup",
    "categorie": "education",
    "sous_categorie": "enseignement_superieur",
    "public": ["jeunes"],
    "resume": "Suppression de Parcoursup, accès sans sélection à l'université pour tous les bacheliers.",
    "explication": "Parcoursup est supprimé. Tout bachelier peut s'inscrire dans la formation de son choix. Les capacités d'accueil des universités sont augmentées pour répondre aux besoins.",
    "chiffre_cle": "76% des Français soutiennent la suppression de Parcoursup",
    "exemple_concret": "Un bachelier peut s'inscrire directement en licence de psychologie, sans passer par un algorithme de sélection.",
    "financement": "Augmentation des moyens des universités (30 000 recrutements)",
    "url": "/2100/mesures/fin-parcoursup.html",
    "motscles": ["Parcoursup", "université", "sélection", "bachelier", "études supérieures"],
    "statut": "mesure_cle"
  },
  {
    "id": 30,
    "titre": "Recrutement de 160 000 enseignants",
    "categorie": "education",
    "sous_categorie": "personnels",
    "public": ["jeunes", "parents"],
    "resume": "Recrutement massif d'enseignants pour réduire les effectifs par classe.",
    "explication": "160 000 enseignants sont recrutés sur le quinquennat pour atteindre une moyenne de 19 élèves par classe (contre 24 aujourd'hui dans certains établissements). Priorité aux maternelles et aux REP.",
    "chiffre_cle": "60 000 recrutements immédiats dès la première année",
    "exemple_concret": "Dans une école maternelle de REP, une classe de 30 élèves passe à 19 élèves avec deux enseignants.",
    "financement": "26,5 milliards d'euros par an",
    "url": "/2100/mesures/recrutement-enseignants.html",
    "motscles": ["enseignant", "recrutement", "effectifs", "classe", "REP"],
    "statut": "mesure_cle"
  },
  {
    "id": 31,
    "titre": "Gratuité des cantines et fournitures scolaires",
    "categorie": "education",
    "sous_categorie": "gratuite",
    "public": ["parents", "jeunes"],
    "resume": "Cantines scolaires gratuites, fournitures et manuels gratuits.",
    "explication": "L'école devient réellement gratuite : cantine, fournitures, manuels, transports scolaires, sorties. Fin des inégalités entre élèves.",
    "chiffre_cle": "67% des Français soutiennent la gratuité intégrale de l'école",
    "exemple_concret": "Une famille avec 3 enfants ne paie plus 600€ par an de cantine et 300€ de fournitures.",
    "financement": "5,2 milliards d'euros par an",
    "url": "/2100/mesures/gratuite-ecole.html",
    "motscles": ["cantine", "fournitures", "gratuité", "école", "manuels"],
    "statut": "mesure"
  },
  {
    "id": 32,
    "titre": "Bac pro en 4 ans",
    "categorie": "education",
    "sous_categorie": "professionnel",
    "public": ["jeunes"],
    "resume": "Rétablissement du bac professionnel en 4 ans avec renforcement des enseignements généraux.",
    "explication": "Le bac pro repasse à 4 ans (contre 3 ans actuellement). Les enseignements généraux sont renforcés pour une meilleure qualification durable.",
    "chiffre_cle": "La moitié des lycéens sont en voie professionnelle",
    "exemple_concret": "Un élève de bac pro cuisine a 4 ans pour apprendre son métier et consolider son français, maths et histoire.",
    "financement": "5 milliards d'euros d'investissement dans les lycées professionnels",
    "url": "/2100/mesures/bac-pro-4-ans.html",
    "motscles": ["bac pro", "enseignement professionnel", "lycée pro", "CAP", "formation"],
    "statut": "mesure"
  },
  {
    "id": 33,
    "titre": "Garantie d'autonomie pour les étudiants",
    "categorie": "education",
    "sous_categorie": "etudiants",
    "public": ["jeunes"],
    "resume": "1063€ par mois pour tout étudiant détaché du foyer fiscal parental.",
    "explication": "Les étudiants reçoivent une garantie d'autonomie de 1063€ net par mois (seuil de pauvreté). Fin de la précarité étudiante et des petits boulots qui nuisent aux études.",
    "chiffre_cle": "23% des 18-24 ans vivent sous le seuil de pauvreté",
    "exemple_concret": "Un étudiant en master peut se concentrer sur ses études sans travailler 20h/semaine en livraison.",
    "financement": "Inclus dans le plan pauvreté",
    "url": "/2100/mesures/garantie-autonomie-etudiants.html",
    "motscles": ["étudiant", "précarité", "bourse", "autonomie", "seuil de pauvreté"],
    "statut": "mesure_cle"
  },

  // === LOGEMENT (5) ===
  {
    "id": 34,
    "titre": "200 000 logements publics par an",
    "categorie": "logement",
    "sous_categorie": "social",
    "public": ["tous", "precaires", "jeunes"],
    "resume": "Construction massive de logements publics : 200 000 par an pendant 5 ans.",
    "explication": "La construction de logements sociaux est relancée : 200 000 par an, dont 15 000 logements étudiants. Priorité aux normes écologiques (bâtiments à énergie positive).",
    "chiffre_cle": "2 millions de familles en attente d'un logement social",
    "exemple_concret": "Une famille de 4 personnes en attente depuis 3 ans se voit proposer un appartement neuf bien isolé.",
    "financement": "15 milliards d'euros sur le quinquennat",
    "url": "/2100/mesures/construction-logements-publics.html",
    "motscles": ["HLM", "logement social", "construction", "logement public", "bailleurs sociaux"],
    "statut": "mesure_cle"
  },
  {
    "id": 35,
    "titre": "Encadrement des loyers",
    "categorie": "logement",
    "sous_categorie": "location",
    "public": ["tous", "jeunes", "precaires"],
    "resume": "Encadrement des loyers partout, avec décote de 20% dans les zones très tendues.",
    "explication": "Les loyers sont encadrés sur tout le territoire. Dans les zones très tendues (Paris, Lyon, Bordeaux...), le loyer maximal est fixé à 20% en dessous du loyer médian.",
    "chiffre_cle": "Les loyers ont augmenté de 44% dans le privé en 10 ans",
    "exemple_concret": "À Paris, un 2 pièces loué 1200€ voit son loyer plafonné à 960€.",
    "financement": "Sans coût pour l'État - transfert des propriétaires vers les locataires",
    "url": "/2100/mesures/encadrement-loyers.html",
    "motscles": ["loyer", "encadrement", "location", "propriétaire", "locataire"],
    "statut": "mesure"
  },
  {
    "id": 36,
    "titre": "Interdiction des expulsions sans relogement",
    "categorie": "logement",
    "sous_categorie": "location",
    "public": ["precaires", "tous"],
    "resume": "Plus aucune expulsion locative sans proposition de relogement public.",
    "explication": "L'expulsion d'un locataire est interdite si l'État ne peut pas proposer une solution de relogement public (HLM, pension de famille, hébergement).",
    "chiffre_cle": "300 000 personnes sans domicile fixe en France",
    "exemple_concret": "Une famille avec 2 enfants ne peut pas être mise à la rue ; l'État doit leur trouver un logement de substitution.",
    "financement": "2 milliards d'euros par an",
    "url": "/2100/mesures/interdiction-expulsions.html",
    "motscles": ["expulsion", "relogement", "DALO", "sans-abri", "logement"],
    "statut": "mesure_cle"
  },
  {
    "id": 37,
    "titre": "Zéro sans-abri",
    "categorie": "logement",
    "sous_categorie": "social",
    "public": ["precaires"],
    "resume": "Plan d'urgence pour sortir 300 000 personnes de la rue et des hébergements d'urgence.",
    "explication": "Objectif 'zéro sans-abri' : réquisition des logements vacants, création de pensions de famille, logement d'abord pour tous.",
    "chiffre_cle": "3,1 millions de logements vacants en France",
    "exemple_concret": "Un SDF suivi par le 115 se voit proposer un logement, pas juste une nuit d'hôtel.",
    "financement": "3,7 milliards d'euros par an",
    "url": "/2100/mesures/zero-sans-abri.html",
    "motscles": ["SDF", "sans-abri", "rue", "hébergement d'urgence", "115"],
    "statut": "mesure_cle"
  },
  {
    "id": 38,
    "titre": "Rénovation obligatoire des passoires thermiques",
    "categorie": "logement",
    "sous_categorie": "renovation",
    "public": ["tous", "precaires"],
    "resume": "Les logements classés F et G ne peuvent plus être loués sans rénovation complète.",
    "explication": "Les passoires thermiques (étiquettes F et G du DPE) doivent être rénovées avant d'être remises en location. Aides de l'État pour les propriétaires modestes.",
    "chiffre_cle": "4,8 millions de logements sont des passoires thermiques",
    "exemple_concret": "Un propriétaire d'un appartement classé G doit l'isoler avant de pouvoir le relouer.",
    "financement": "Inclus dans le plan rénovation thermique",
    "url": "/2100/mesures/renovation-passoires-thermiques.html",
    "motscles": ["passoire thermique", "DPE", "rénovation", "isolation", "location"],
    "statut": "mesure"
  },

  // === DÉMOCRATIE & JUSTICE (6) ===
  {
    "id": 39,
    "titre": "6e République",
    "categorie": "democratie",
    "sous_categorie": "institutions",
    "public": ["tous"],
    "resume": "Convocation d'une Assemblée constituante pour écrire une nouvelle Constitution.",
    "explication": "Une Assemblée constituante, composée de citoyens élus et tirés au sort, rédige une nouvelle Constitution. Le projet est soumis à référendum. Fin de la monarchie présidentielle, régime parlementaire.",
    "chiffre_cle": "63% des Français soutiennent une nouvelle Constitution",
    "exemple_concret": "Les citoyens participent à l'écriture des règles du jeu démocratique via des cahiers de doléances.",
    "financement": "300 millions d'euros pour le référendum, 500 millions par an pour la Constituante",
    "url": "/2100/mesures/6e-republique.html",
    "motscles": ["6e République", "Constituante", "Constitution", "démocratie", "référendum"],
    "statut": "mesure_cle"
  },
  {
    "id": 40,
    "titre": "Référendum d'initiative citoyenne (RIC)",
    "categorie": "democratie",
    "sous_categorie": "institutions",
    "public": ["tous"],
    "resume": "Les citoyens peuvent proposer des lois, abroger des textes ou révoquer des élus.",
    "explication": "Le RIC permet à des citoyens réunissant suffisamment de signatures de : proposer une loi, abroger une loi existante, révoquer un élu en cours de mandat.",
    "chiffre_cle": "69% des Français soutiennent le RIC",
    "exemple_concret": "Les Gilets jaunes auraient pu proposer le RIC qu'ils réclamaient.",
    "financement": "Sans coût supplémentaire - organisation de référendums",
    "url": "/2100/mesures/ric.html",
    "motscles": ["RIC", "référendum", "initiative citoyenne", "révocation", "démocratie directe"],
    "statut": "mesure_cle"
  },
  {
    "id": 41,
    "titre": "Sortie de l'OTAN",
    "categorie": "international",
    "sous_categorie": "defense",
    "public": ["tous"],
    "resume": "Retrait de la France du commandement intégré de l'OTAN puis de l'organisation.",
    "explication": "La France quitte l'OTAN pour retrouver sa souveraineté militaire et diplomatique. Elle devient non-alignée, au service de la paix et du droit international.",
    "chiffre_cle": "96% des Français soutiennent le retrait de l'OTAN selon certains sondages",
    "exemple_concret": "La France n'est plus entraînée dans des guerres décidées par les États-Unis.",
    "financement": "Économies sur les contributions à l'OTAN",
    "url": "/2100/mesures/sortie-otan.html",
    "motscles": ["OTAN", "défense", "souveraineté", "non-alignement", "paix"],
    "statut": "mesure"
  },
  {
    "id": 42,
    "titre": "Proportionnelle aux législatives",
    "categorie": "democratie",
    "sous_categorie": "institutions",
    "public": ["tous"],
    "resume": "Élection des députés à la proportionnelle intégrale.",
    "explication": "Les élections législatives se font à la proportionnelle intégrale. Fin du scrutin majoritaire qui élimine les petites formations politiques.",
    "chiffre_cle": "68% des Français soutiennent la proportionnelle",
    "exemple_concret": "Un parti qui obtient 10% des voix a 10% des sièges à l'Assemblée.",
    "financement": "Sans coût - réorganisation des circonscriptions",
    "url": "/2100/mesures/proportionnelle-legislatives.html",
    "motscles": ["proportionnelle", "législatives", "députés", "scrutin", "Assemblée nationale"],
    "statut": "mesure"
  },
  {
    "id": 43,
    "titre": "Droit de vote à 16 ans",
    "categorie": "democratie",
    "sous_categorie": "institutions",
    "public": ["jeunes"],
    "resume": "Le droit de vote est accordé à partir de 16 ans.",
    "explication": "Les jeunes de 16 et 17 ans peuvent voter à toutes les élections. Ils sont déjà imposables, peuvent travailler, être émancipés. Cette mesure élargit le corps électoral de 1,5 million de personnes.",
    "chiffre_cle": "87% d'abstention chez les 18-24 ans (fatigue démocratique précoce)",
    "exemple_concret": "Un lycéen de 17 ans vote pour la première fois à la présidentielle.",
    "financement": "Sans coût - mise à jour des listes électorales",
    "url": "/2100/mesures/droit-vote-16-ans.html",
    "motscles": ["vote", "16 ans", "jeunes", "élections", "citoyenneté"],
    "statut": "mesure"
  },
  {
    "id": 44,
    "titre": "Fin de l'état d'urgence permanent",
    "categorie": "democratie",
    "sous_categorie": "liberte",
    "public": ["tous"],
    "resume": "Abrogation de l'état d'urgence sanitaire et sécuritaire, retour au droit commun.",
    "explication": "Fin des états d'urgence qui se sont installés dans la durée. Abrogation des lois liberticides (SILT, sécurité globale, loi renseignement). Retour aux garanties démocratiques normales.",
    "chiffre_cle": "24 lois liberticides adoptées entre 2017 et 2024",
    "exemple_concret": "Fin des contrôles d'identité abusifs sans motif, fin du pass sanitaire.",
    "financement": "Sans coût",
    "url": "/2100/mesures/fin-etat-urgence.html",
    "motscles": ["état d'urgence", "libertés", "sécurité globale", "renseignement", "pass sanitaire"],
    "statut": "mesure"
  },

  // === FISCALITÉ (6 - complétée) ===
  {
    "id": 45,
    "titre": "Rétablissement de l'ISF",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["riches"],
    "resume": "Rétablissement de l'Impôt de Solidarité sur la Fortune (ISF).",
    "explication": "L'ISF supprimé par Macron est rétabli avec un barème progressif. Il rapporte 10 milliards d'euros par an.",
    "chiffre_cle": "78% des Français soutiennent le rétablissement de l'ISF",
    "exemple_concret": "Une personne avec 2 millions d'euros de patrimoine paie à nouveau l'ISF.",
    "financement": "10 milliards d'euros par an",
    "url": "/2100/mesures/retablissement-isf.html",
    "motscles": ["ISF", "impôt", "fortune", "riches", "patrimoine"],
    "statut": "mesure_cle"
  },
  {
    "id": 46,
    "titre": "Impôt sur le revenu à 14 tranches",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["tous"],
    "resume": "Barème de l'impôt sur le revenu élargi à 14 tranches (comme en 1983).",
    "explication": "L'impôt sur le revenu redevient fortement progressif : 14 tranches contre 5 actuellement. Taux marginal à 90% pour les revenus > 400 000€/an. Baisse d'impôt pour les revenus < 4000€/mois.",
    "chiffre_cle": "Les 10% les plus riches paient proportionnellement moins d'impôts que les 10% les plus pauvres",
    "exemple_concret": "Un smicard ne paie plus d'impôt sur le revenu.",
    "financement": "5 milliards d'euros de recettes supplémentaires par an",
    "url": "/2100/mesures/impot-revenu-14-tranches.html",
    "motscles": ["impôt sur le revenu", "progressivité", "tranches", "barème", "IR"],
    "statut": "mesure_cle"
  },
  {
    "id": 47,
    "titre": "Suppression de la flat tax",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["riches"],
    "resume": "Suppression de la flat tax (PFU) sur les revenus du capital.",
    "explication": "La flat tax à 30% sur les revenus du capital (dividendes, plus-values) est supprimée. Les revenus du capital sont imposés comme ceux du travail, avec le barème progressif de l'IR.",
    "chiffre_cle": "La flat tax a coûté 3,5 milliards par an aux finances publiques",
    "exemple_concret": "Un rentier qui vit de ses dividendes paie désormais l'impôt comme un salarié.",
    "financement": "1,8 milliard d'euros par an",
    "url": "/2100/mesures/suppression-flat-tax.html",
    "motscles": ["flat tax", "PFU", "capital", "dividendes", "plus-values"],
    "statut": "mesure"
  },
  {
    "id": 48,
    "titre": "Héritage maximum à 12 millions d'euros",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["riches"],
    "resume": "Plafonnement de l'héritage à 12 millions d'euros par personne.",
    "explication": "Au-delà de 12 millions d'euros d'héritage (100 fois le patrimoine médian), tout est reversé à l'État pour financer la garantie d'autonomie des jeunes.",
    "chiffre_cle": "Le top 0,1% des héritiers reçoit 180 fois l'héritage médian",
    "exemple_concret": "Un héritier qui reçoit 15 millions d'euros garde 12 millions, les 3 millions vont à l'État.",
    "financement": "17 milliards d'euros par an",
    "url": "/2100/mesures/heritage-maximum.html",
    "motscles": ["héritage", "succession", "donation", "transmission", "patrimoine"],
    "statut": "mesure"
  },
  {
    "id": 49,
    "titre": "Taxe sur les superprofits",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["entreprises"],
    "resume": "Taxe exceptionnelle de 50% sur les superprofits des grandes entreprises.",
    "explication": "Les entreprises réalisant des bénéfices exceptionnels (par rapport à la moyenne des 5 années précédentes) paient une taxe de 50% sur ces superprofits.",
    "chiffre_cle": "TotalEnergies a réalisé 36 milliards de bénéfices en 2022",
    "exemple_concret": "Une entreprise qui double ses bénéfices paie 50% sur la moitié excédentaire.",
    "financement": "Recette ponctuelle non chiffrée",
    "url": "/2100/mesures/taxe-superprofits.html",
    "motscles": ["superprofit", "taxe", "entreprise", "bénéfice", "crise"],
    "statut": "mesure"
  },
  {
    "id": 50,
    "titre": "Impôt universel sur les multinationales",
    "categorie": "economie",
    "sous_categorie": "fiscalite",
    "public": ["entreprises"],
    "resume": "Les multinationales paient l'impôt sur les sociétés en fonction de leur activité en France.",
    "explication": "Les multinationales sont taxées sur la part de leur activité réalisée en France, où qu'elles soient domiciliées. Fin de l'optimisation fiscale via l'Irlande, le Luxembourg ou les paradis fiscaux.",
    "chiffre_cle": "26 milliards d'euros d'évasion fiscale par an",
    "exemple_concret": "Google paie l'IS sur les 10% de ses ventes mondiales réalisées en France.",
    "financement": "26 milliards d'euros par an",
    "url": "/2100/mesures/impot-universel-multinationales.html",
    "motscles": ["multinationales", "évasion fiscale", "impôt sur les sociétés", "GAFA", "paradis fiscaux"],
    "statut": "mesure_cle"
  }
];

// Export pour utilisation
if (typeof module !== 'undefined' && module.exports) {
  module.exports = mesures;
}
